#!/usr/bin/env python3
"""Append 100+ more supplements to supplements.ts to reach 200+ total."""

import re

NEW_SUPPLEMENTS = '''
  // ─── TCM HERBS ────────────────────────────────────────────────────────────
  {
    id: 'dong-quai',
    name: 'Dong Quai (Angelica sinensis)',
    category: 'TCM Herbs',
    subcategory: 'Blood Tonics',
    description: 'Dong quai is the most widely used herb in Traditional Chinese Medicine for women\'s reproductive health, often called the "female ginseng" for its ability to nourish and move blood. It contains ferulic acid and ligustilide, which relax uterine muscle, reduce menstrual cramping, and support circulation to the pelvic organs. In TCM, it is used for blood deficiency patterns that manifest as pelvic pain, scanty periods, and postpartum recovery.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/dong-quai.webp',
    tags: ['TCM', 'menstrual-pain', 'blood-tonic', 'postpartum', 'pelvic-circulation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Menstrual regulation and pelvic circulation',
  },
  {
    id: 'bai-shao',
    name: 'White Peony Root (Bai Shao)',
    category: 'TCM Herbs',
    subcategory: 'Blood Tonics',
    description: 'White peony root is a foundational TCM herb for nourishing liver blood and softening the liver, which in Chinese medicine governs the smooth flow of qi through the pelvis and reproductive organs. Paeoniflorin, its primary compound, has demonstrated anti-spasmodic, anti-inflammatory, and hormone-modulating effects in clinical research. It is commonly combined with licorice root (Shao Yao Gan Cao Tang) for pelvic cramping, vaginismus, and hypertonic pelvic floor conditions.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/bai-shao.webp',
    tags: ['TCM', 'liver-blood', 'anti-spasmodic', 'vaginismus', 'hypertonic-pelvic-floor'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Pelvic muscle spasm and liver blood nourishment',
  },
  {
    id: 'chuan-xiong',
    name: 'Chuan Xiong (Ligusticum chuanxiong)',
    category: 'TCM Herbs',
    subcategory: 'Blood Movers',
    description: 'Chuan xiong is one of the primary blood-moving herbs in TCM, used to invigorate blood circulation and relieve pain in the lower abdomen and pelvis. Its active compounds tetramethylpyrazine and ferulic acid have vasodilatory, anti-platelet, and analgesic properties that support pelvic blood flow and reduce stagnation-type pain. It is frequently combined with dong quai in formulas for endometriosis, dysmenorrhea, and pelvic congestion syndrome.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/chuan-xiong.webp',
    tags: ['TCM', 'blood-moving', 'endometriosis', 'pelvic-pain', 'dysmenorrhea'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Blood stagnation and pelvic pain',
  },
  {
    id: 'yi-mu-cao',
    name: 'Motherwort (Yi Mu Cao)',
    category: 'TCM Herbs',
    subcategory: 'Uterine Tonics',
    description: 'Motherwort is used in both TCM and Western herbalism as a uterine tonic that moves blood, reduces cramping, and supports postpartum uterine involution. Leonurine, its primary alkaloid, stimulates uterine contractions and has demonstrated anti-platelet and cardioprotective effects in research. It is traditionally used for delayed periods, postpartum recovery, and pelvic stagnation patterns with a sensation of heaviness or fullness.',
    asin: 'B00FIOD9UE',
    imageKey: 'supplements/motherwort.webp',
    tags: ['TCM', 'uterine-tonic', 'postpartum', 'menstrual-regulation', 'pelvic-stagnation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine health and postpartum recovery',
  },
  {
    id: 'tu-si-zi',
    name: 'Cuscuta Seed (Tu Si Zi)',
    category: 'TCM Herbs',
    subcategory: 'Kidney Yang Tonics',
    description: 'Cuscuta seed tonifies kidney yang and essence in TCM, making it relevant for urinary incontinence, frequent urination, and pelvic floor weakness associated with kidney deficiency patterns. Research has shown it contains flavonoids that support estrogen-like activity, bone density, and reproductive organ health. It is commonly used in formulas for stress urinary incontinence, nocturia, and postmenopausal pelvic floor changes.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/tu-si-zi.webp',
    tags: ['TCM', 'kidney-yang', 'incontinence', 'urinary-frequency', 'menopause'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Kidney yang and urinary incontinence',
  },
  {
    id: 'huang-qi',
    name: 'Astragalus Root (Huang Qi)',
    category: 'TCM Herbs',
    subcategory: 'Qi Tonics',
    description: 'Astragalus is a premier qi tonic in TCM that strengthens the spleen and lung qi, which in Chinese medicine supports the lifting and holding function relevant to pelvic organ prolapse and urinary incontinence. Its polysaccharides and saponins have demonstrated immune-modulating, anti-inflammatory, and adaptogenic effects in extensive research. It is used in formulas for prolapse, chronic fatigue, and pelvic floor weakness from a qi deficiency pattern.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/astragalus.webp',
    tags: ['TCM', 'qi-tonic', 'prolapse', 'immune-support', 'adaptogen'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Qi deficiency and pelvic organ support',
  },
  {
    id: 'shan-yao',
    name: 'Chinese Yam (Shan Yao)',
    category: 'TCM Herbs',
    subcategory: 'Kidney & Spleen Tonics',
    description: 'Chinese yam tonifies both kidney and spleen qi and yin in TCM, making it a gentle tonic for the entire reproductive and urinary system. It contains diosgenin, a steroidal saponin that serves as a precursor to progesterone and DHEA, supporting hormonal balance in perimenopause and menopause. It is used for vaginal dryness, urinary frequency, and general pelvic floor weakness associated with deficiency patterns.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/shan-yao.webp',
    tags: ['TCM', 'kidney-yin', 'vaginal-dryness', 'hormonal-balance', 'menopause'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Kidney and spleen tonic for reproductive health',
  },
  {
    id: 'ze-xie',
    name: 'Alisma (Ze Xie)',
    category: 'TCM Herbs',
    subcategory: 'Dampness-Clearing',
    description: 'Alisma is a TCM herb that drains dampness and clears heat from the lower jiao, the energetic zone corresponding to the bladder, kidneys, and reproductive organs. It has diuretic, anti-inflammatory, and lipid-lowering properties, and is used for urinary tract infections, interstitial cystitis, and bladder irritability with heat signs. In formulas like Liu Wei Di Huang Wan, it balances the tonifying herbs to prevent stagnation.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/ze-xie.webp',
    tags: ['TCM', 'dampness', 'UTI', 'interstitial-cystitis', 'bladder-heat'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Bladder heat and urinary tract inflammation',
  },
  {
    id: 'fu-ling',
    name: 'Poria Mushroom (Fu Ling)',
    category: 'TCM Herbs',
    subcategory: 'Dampness-Resolving',
    description: 'Poria is one of the most commonly used herbs in TCM, appearing in hundreds of classical formulas for its ability to calm the mind, strengthen the spleen, and resolve dampness. Its beta-glucans have demonstrated significant immune-modulating and anti-inflammatory effects in modern research. For pelvic health, it is used in formulas addressing vaginal discharge, urinary frequency, and anxiety-related pelvic floor tension.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/poria.webp',
    tags: ['TCM', 'dampness', 'vaginal-discharge', 'anxiety', 'immune-support'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Dampness resolution and nervous system calm',
  },
  {
    id: 'gui-zhi',
    name: 'Cinnamon Twig (Gui Zhi)',
    category: 'TCM Herbs',
    subcategory: 'Yang-Warming',
    description: 'Cinnamon twig warms and unblocks the channels in TCM, making it central to formulas for cold-type pelvic pain, endometriosis with cold patterns, and poor circulation to the pelvic organs. Cinnamaldehyde has demonstrated anti-inflammatory, vasodilatory, and insulin-sensitizing effects relevant to conditions like PCOS that affect pelvic floor function. The classical formula Gui Zhi Fu Ling Wan uses it specifically for uterine blood stagnation and pelvic masses.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/gui-zhi.webp',
    tags: ['TCM', 'cold-pelvic-pain', 'endometriosis', 'PCOS', 'blood-stagnation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Cold-type pelvic pain and blood stagnation',
  },
  // ─── AYURVEDIC HERBS ──────────────────────────────────────────────────────
  {
    id: 'shatavari',
    name: 'Shatavari (Asparagus racemosus)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Rasayanas',
    description: 'Shatavari is the primary Ayurvedic herb for women\'s reproductive health, its name meaning "she who possesses a hundred husbands" in reference to its profound support for female vitality and fertility. Its steroidal saponins (shatavarin I-IV) have demonstrated estrogen-modulating, anti-inflammatory, and adaptogenic effects, making it relevant for vaginal dryness, perimenopause, and pelvic tissue health. It is used throughout a woman\'s life cycle for menstrual regulation, postpartum recovery, and menopausal transition.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/shatavari.webp',
    tags: ['Ayurveda', 'estrogen', 'vaginal-dryness', 'menopause', 'postpartum'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Female reproductive vitality and hormonal balance',
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha (Withania somnifera)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Adaptogens',
    description: 'Ashwagandha is the most researched Ayurvedic adaptogen, with extensive clinical evidence for reducing cortisol, improving stress resilience, and supporting thyroid and adrenal function. Chronic stress and elevated cortisol directly impair pelvic floor function by maintaining the nervous system in a sympathetic (fight-or-flight) state that prevents pelvic muscle relaxation. Multiple RCTs have confirmed its ability to reduce anxiety, improve sleep, and lower cortisol, all of which support pelvic floor healing.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/ashwagandha.webp',
    tags: ['adaptogen', 'cortisol', 'stress', 'nervous-system', 'thyroid'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Stress reduction and nervous system regulation',
  },
  {
    id: 'triphala',
    name: 'Triphala',
    category: 'Ayurvedic Herbs',
    subcategory: 'Digestive Tonics',
    description: 'Triphala is a classical Ayurvedic formula of three fruits (amalaki, bibhitaki, haritaki) used as a gentle bowel tonic and digestive support that is directly relevant to pelvic floor health. Chronic constipation and straining are among the most damaging habits for the pelvic floor, contributing to prolapse, hemorrhoids, and pudendal nerve irritation. Triphala\'s gentle laxative and prebiotic effects normalize bowel function without creating dependency, reducing the straining that damages pelvic floor structures.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/triphala.webp',
    tags: ['Ayurveda', 'constipation', 'bowel-health', 'prolapse-prevention', 'digestive'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bowel regularity and constipation relief',
  },
  {
    id: 'guduchi',
    name: 'Guduchi (Tinospora cordifolia)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Immune Tonics',
    description: 'Guduchi is an Ayurvedic herb known as "the divine nectar" for its immune-modulating, anti-inflammatory, and adaptogenic properties. Research has demonstrated its ability to reduce inflammatory cytokines relevant to conditions like interstitial cystitis, endometriosis, and chronic pelvic pain syndrome. It is used in Ayurveda for conditions involving ama (toxic accumulation) and chronic inflammation in the lower abdomen and reproductive organs.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/guduchi.webp',
    tags: ['Ayurveda', 'anti-inflammatory', 'interstitial-cystitis', 'endometriosis', 'immune'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Chronic pelvic inflammation and immune modulation',
  },
  {
    id: 'brahmi',
    name: 'Brahmi (Bacopa monnieri)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Nervines',
    description: 'Brahmi is the primary Ayurvedic nervine tonic, used to calm the nervous system, reduce anxiety, and improve cognitive function. The pelvic floor is profoundly influenced by the autonomic nervous system, and chronic anxiety maintains a hypertonic (too-tight) pelvic floor that resists relaxation. Bacosides, brahmi\'s active compounds, have demonstrated anxiolytic effects comparable to benzodiazepines in some studies, without the dependency risk.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/brahmi.webp',
    tags: ['Ayurveda', 'nervine', 'anxiety', 'hypertonic-pelvic-floor', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Nervous system calm and hypertonic pelvic floor',
  },
  {
    id: 'lodhra',
    name: 'Lodhra (Symplocos racemosa)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Uterine Astringents',
    description: 'Lodhra is a classical Ayurvedic uterine astringent used for excessive menstrual bleeding, vaginal discharge, and pelvic organ prolapse. Its tannins and alkaloids have demonstrated uterine-toning, anti-inflammatory, and estrogenic effects in research. In Ayurveda it is considered a specific remedy for conditions involving laxity and downward displacement of pelvic organs.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/lodhra.webp',
    tags: ['Ayurveda', 'uterine-tonic', 'prolapse', 'menorrhagia', 'vaginal-discharge'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine tone and pelvic organ support',
  },
  {
    id: 'vidari-kanda',
    name: 'Vidari Kanda (Pueraria tuberosa)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Rasayanas',
    description: 'Vidari kanda is an Ayurvedic rasayana (rejuvenative) herb for female reproductive tissue, containing isoflavones and phytoestrogens that support vaginal tissue health and hormonal balance. It is used for vaginal atrophy, decreased libido, and postmenopausal pelvic changes where tissue thinning contributes to pain and dysfunction. Its anabolic and tissue-building properties make it relevant for postpartum recovery and rebuilding pelvic floor strength.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/vidari-kanda.webp',
    tags: ['Ayurveda', 'phytoestrogens', 'vaginal-atrophy', 'menopause', 'postpartum'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Vaginal tissue health and phytoestrogenic support',
  },
  // ─── WESTERN HERBS ────────────────────────────────────────────────────────
  {
    id: 'cramp-bark',
    name: 'Cramp Bark (Viburnum opulus)',
    category: 'Western Herbs',
    subcategory: 'Antispasmodics',
    description: 'Cramp bark is one of the most effective Western herbal antispasmodics for the uterus and pelvic floor, used for menstrual cramping, vaginismus, and hypertonic pelvic floor conditions. Its active compounds viopudial and scopoletin relax smooth and skeletal muscle, reducing spasm and pain without sedation. It is particularly useful for the type of pelvic floor tension that worsens with anxiety and stress.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/cramp-bark.webp',
    tags: ['antispasmodic', 'vaginismus', 'menstrual-pain', 'hypertonic-pelvic-floor', 'muscle-relaxant'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine and pelvic muscle spasm',
  },
  {
    id: 'black-cohosh',
    name: 'Black Cohosh (Actaea racemosa)',
    category: 'Western Herbs',
    subcategory: 'Menopause Support',
    description: 'Black cohosh is the most researched Western herb for menopausal symptoms, with multiple clinical trials demonstrating its ability to reduce hot flashes, night sweats, and vaginal dryness. Its mechanism involves serotonergic rather than estrogenic pathways, making it potentially safer than phytoestrogens for women with hormone-sensitive conditions. For pelvic floor health, its reduction of vaginal atrophy and dryness directly addresses pain with intercourse and urinary symptoms in menopause.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/black-cohosh.webp',
    tags: ['menopause', 'hot-flashes', 'vaginal-dryness', 'dyspareunia', 'Western-herbs'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Menopausal symptoms and vaginal atrophy',
  },
  {
    id: 'wild-yam',
    name: 'Wild Yam (Dioscorea villosa)',
    category: 'Western Herbs',
    subcategory: 'Hormonal Support',
    description: 'Wild yam contains diosgenin, a steroidal saponin that is a laboratory precursor to progesterone, though the human body cannot convert it directly. Topical wild yam creams are widely used for menopausal symptoms and are thought to work through skin absorption of diosgenin and its metabolites. For pelvic health, it is used for progesterone deficiency patterns, including PMS, luteal phase deficiency, and perimenopausal pelvic floor changes.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/wild-yam.webp',
    tags: ['progesterone', 'menopause', 'PMS', 'hormonal-balance', 'Western-herbs'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Progesterone support and hormonal balance',
  },
  {
    id: 'red-raspberry-leaf',
    name: 'Red Raspberry Leaf',
    category: 'Western Herbs',
    subcategory: 'Uterine Tonics',
    description: 'Red raspberry leaf is a traditional uterine tonic used throughout pregnancy and postpartum recovery for its ability to tone uterine muscle and support pelvic floor strength. Its fragarine alkaloid has demonstrated uterine-toning effects, and its high mineral content (calcium, magnesium, iron) supports muscle function throughout the pelvic region. It is widely used in the third trimester to prepare the uterus for labor and postpartum for uterine involution.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/red-raspberry-leaf.webp',
    tags: ['uterine-tonic', 'postpartum', 'pregnancy', 'pelvic-floor-strength', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine tone and postpartum recovery',
  },
  {
    id: 'ladies-mantle',
    name: 'Lady\'s Mantle (Alchemilla vulgaris)',
    category: 'Western Herbs',
    subcategory: 'Uterine Astringents',
    description: 'Lady\'s mantle is a traditional European herb for women\'s reproductive health, used as a uterine astringent for heavy periods, vaginal discharge, and pelvic organ prolapse. Its tannins tone and tighten pelvic tissues, while its progesterogenic effects support the luteal phase and reduce estrogen dominance patterns. It is often combined with shepherd\'s purse for heavy bleeding and with cramp bark for dysmenorrhea.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/ladys-mantle.webp',
    tags: ['uterine-tonic', 'prolapse', 'heavy-periods', 'progesterone', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine astringency and pelvic tissue tone',
  },
  {
    id: 'corn-silk',
    name: 'Corn Silk (Zea mays)',
    category: 'Western Herbs',
    subcategory: 'Urinary Demulcents',
    description: 'Corn silk is a gentle urinary demulcent and diuretic used for bladder irritation, urinary frequency, and mild urinary tract infections. Its mucilaginous compounds coat and soothe the bladder lining, reducing the urgency and burning associated with interstitial cystitis and overactive bladder. It is one of the safest urinary herbs for long-term use and is appropriate for women with sensitive bladders who react to many foods and supplements.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/corn-silk.webp',
    tags: ['urinary-demulcent', 'interstitial-cystitis', 'overactive-bladder', 'UTI', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Bladder soothing and urinary frequency',
  },
  {
    id: 'uva-ursi',
    name: 'Uva Ursi (Arctostaphylos uva-ursi)',
    category: 'Western Herbs',
    subcategory: 'Urinary Antiseptics',
    description: 'Uva ursi is a traditional urinary antiseptic herb containing arbutin, which converts to hydroquinone in alkaline urine and has demonstrated antibacterial activity against common UTI pathogens. It is used for acute urinary tract infections and as a preventive for recurrent UTIs that contribute to pelvic floor dysfunction through chronic inflammation. It requires an alkaline urine pH to activate, so it is often combined with sodium bicarbonate or dietary alkalinization.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/uva-ursi.webp',
    tags: ['UTI', 'urinary-antiseptic', 'recurrent-UTI', 'bladder-health', 'Western-herbs'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Urinary tract infection and prevention',
  },
  {
    id: 'goldenrod',
    name: 'Goldenrod (Solidago virgaurea)',
    category: 'Western Herbs',
    subcategory: 'Urinary Tonics',
    description: 'Goldenrod is a European urinary tonic with anti-inflammatory, antispasmodic, and mild diuretic properties used for bladder inflammation, kidney stones, and urinary tract infections. Clinical studies have confirmed its efficacy for reducing bladder inflammation and supporting urinary tract health. It is particularly useful for the type of bladder irritability that accompanies interstitial cystitis and pelvic floor hypertonicity.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/goldenrod.webp',
    tags: ['urinary-tonic', 'bladder-inflammation', 'interstitial-cystitis', 'kidney-stones', 'Western-herbs'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bladder inflammation and urinary tract health',
  },
  {
    id: 'chaste-tree',
    name: 'Chaste Tree Berry (Vitex agnus-castus)',
    category: 'Western Herbs',
    subcategory: 'Hormonal Regulators',
    description: 'Vitex is the most researched Western herb for PMS, PMDD, and progesterone deficiency, with multiple clinical trials demonstrating its ability to reduce luteal phase symptoms by normalizing the LH/FSH ratio and supporting progesterone production. Progesterone deficiency contributes to pelvic floor dysfunction through its effects on connective tissue laxity, bladder sensitivity, and pelvic pain. It requires 3-6 months of consistent use to show full effect.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/vitex.webp',
    tags: ['PMS', 'PMDD', 'progesterone', 'hormonal-balance', 'Western-herbs'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PMS and progesterone deficiency',
  },
  {
    id: 'blue-cohosh',
    name: 'Blue Cohosh (Caulophyllum thalictroides)',
    category: 'Western Herbs',
    subcategory: 'Uterine Stimulants',
    description: 'Blue cohosh is a traditional Native American and eclectic medicine herb used as a uterine tonic and stimulant for conditions involving pelvic stagnation, delayed labor, and postpartum recovery. Its caulosaponin and methylcytisine have demonstrated uterine-stimulating effects, making it appropriate only for specific clinical situations under qualified guidance. It is used in combination formulas for pelvic congestion, chronic pelvic pain with stagnation patterns, and postpartum uterine atony.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/blue-cohosh.webp',
    tags: ['uterine-stimulant', 'pelvic-stagnation', 'postpartum', 'Western-herbs', 'traditional'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine stimulation and pelvic stagnation',
  },
  // ─── ADDITIONAL SUPPLEMENTS ───────────────────────────────────────────────
  {
    id: 'hyaluronic-acid',
    name: 'Hyaluronic Acid (Oral)',
    category: 'Connective Tissue Support',
    subcategory: 'Joint & Tissue Hydration',
    description: 'Oral hyaluronic acid supplementation has demonstrated the ability to increase systemic hyaluronan levels, supporting the hydration and elasticity of connective tissues throughout the body including the pelvic floor fascia and vaginal epithelium. Clinical studies have shown improvement in vaginal dryness and dyspareunia with oral HA supplementation, making it a non-hormonal option for women who cannot use estrogen. It works synergistically with collagen peptides and vitamin C for comprehensive pelvic connective tissue support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/hyaluronic-acid.webp',
    tags: ['connective-tissue', 'vaginal-dryness', 'dyspareunia', 'tissue-hydration', 'menopause'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Vaginal tissue hydration and connective tissue support',
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    category: 'Anti-Inflammatory',
    subcategory: 'Polyphenols',
    description: 'Resveratrol is a polyphenol with potent anti-inflammatory, antioxidant, and estrogen-modulating properties relevant to endometriosis, PCOS, and chronic pelvic inflammation. Multiple studies have demonstrated its ability to reduce endometrial lesion size, lower inflammatory markers, and modulate estrogen receptor activity. It activates SIRT1 pathways that regulate cellular aging, inflammation, and mitochondrial function in pelvic floor tissues.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/resveratrol.webp',
    tags: ['endometriosis', 'PCOS', 'anti-inflammatory', 'estrogen-modulation', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Endometriosis and chronic pelvic inflammation',
  },
  {
    id: 'quercetin',
    name: 'Quercetin',
    category: 'Anti-Inflammatory',
    subcategory: 'Flavonoids',
    description: 'Quercetin is a flavonoid with mast cell-stabilizing properties that make it particularly relevant for interstitial cystitis, vulvodynia, and other conditions involving mast cell activation in pelvic tissues. A clinical trial published in the Journal of Urology demonstrated significant improvement in IC symptoms with quercetin supplementation. It also has anti-inflammatory, antioxidant, and antiviral properties that support overall pelvic tissue health.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/quercetin.webp',
    tags: ['interstitial-cystitis', 'vulvodynia', 'mast-cell', 'anti-inflammatory', 'bladder-health'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Interstitial cystitis and mast cell stabilization',
  },
  {
    id: 'pycnogenol',
    name: 'Pycnogenol (Pine Bark Extract)',
    category: 'Anti-Inflammatory',
    subcategory: 'Proanthocyanidins',
    description: 'Pycnogenol is a standardized extract of French maritime pine bark with potent anti-inflammatory, antioxidant, and vascular-protective properties. Clinical trials have demonstrated its efficacy for endometriosis pain, dysmenorrhea, and pelvic congestion syndrome by reducing prostaglandin synthesis and improving pelvic microcirculation. It also supports collagen synthesis and vascular integrity in pelvic tissues.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/pycnogenol.webp',
    tags: ['endometriosis', 'dysmenorrhea', 'pelvic-congestion', 'anti-inflammatory', 'vascular'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Endometriosis pain and pelvic circulation',
  },
  {
    id: 'n-acetyl-cysteine',
    name: 'N-Acetyl Cysteine (NAC)',
    category: 'Anti-Inflammatory',
    subcategory: 'Antioxidants',
    description: 'NAC is a precursor to glutathione, the body\'s master antioxidant, and has demonstrated clinical efficacy for endometriosis, PCOS, and ovarian cyst reduction in multiple trials. A 2013 Italian trial found NAC more effective than placebo for endometriosis pain and cyst reduction, with some women avoiding surgery. It also supports liver detoxification of excess estrogens, which is relevant to estrogen-driven pelvic conditions.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/nac.webp',
    tags: ['endometriosis', 'PCOS', 'glutathione', 'estrogen-detox', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Endometriosis and PCOS support',
  },
  {
    id: 'berberine',
    name: 'Berberine',
    category: 'Metabolic Support',
    subcategory: 'Alkaloids',
    description: 'Berberine is an alkaloid found in goldenseal, barberry, and Oregon grape with demonstrated efficacy for PCOS, insulin resistance, and gut dysbiosis — all of which significantly impact pelvic floor health. Multiple meta-analyses have confirmed its ability to improve insulin sensitivity, reduce androgens in PCOS, and normalize menstrual cycles. Its antimicrobial properties also support vaginal microbiome health by reducing pathogenic bacteria and yeast.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/berberine.webp',
    tags: ['PCOS', 'insulin-resistance', 'vaginal-microbiome', 'gut-health', 'metabolic'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PCOS and insulin resistance',
  },
  {
    id: 'inositol',
    name: 'Myo-Inositol + D-Chiro-Inositol',
    category: 'Metabolic Support',
    subcategory: 'Insulin Sensitizers',
    description: 'The combination of myo-inositol and D-chiro-inositol in a 40:1 ratio is the most evidence-based nutritional intervention for PCOS, with multiple RCTs demonstrating improvements in insulin sensitivity, ovarian function, androgen levels, and menstrual regularity. PCOS-related hormonal imbalances directly affect pelvic floor function through their effects on connective tissue, bladder sensitivity, and chronic inflammation. It is considered a first-line nutritional intervention for PCOS by many integrative practitioners.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/inositol.webp',
    tags: ['PCOS', 'insulin-resistance', 'ovarian-function', 'hormonal-balance', 'fertility'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PCOS and ovarian function',
  },
  {
    id: 'dim',
    name: 'DIM (Diindolylmethane)',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Metabolism',
    description: 'DIM is a compound derived from cruciferous vegetables that supports the conversion of estradiol to the less potent 2-hydroxyestrone pathway, reducing estrogen dominance and its downstream effects on pelvic tissues. Estrogen dominance contributes to endometriosis, fibroids, adenomyosis, and heavy periods — all of which cause pelvic floor dysfunction. It works synergistically with calcium D-glucarate and sulforaphane for comprehensive estrogen metabolism support.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/dim.webp',
    tags: ['estrogen-dominance', 'endometriosis', 'fibroids', 'hormonal-balance', 'detox'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen metabolism and dominance',
  },
  {
    id: 'calcium-d-glucarate',
    name: 'Calcium D-Glucarate',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Detox',
    description: 'Calcium D-glucarate inhibits beta-glucuronidase, an enzyme produced by gut bacteria that reactivates conjugated estrogens in the intestine, allowing them to be reabsorbed rather than excreted. Elevated beta-glucuronidase activity contributes to estrogen recirculation and dominance, which drives endometriosis, fibroids, and hormonal pelvic pain. It is a foundational supplement for estrogen detoxification pathways and is often combined with DIM and sulforaphane.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/calcium-d-glucarate.webp',
    tags: ['estrogen-detox', 'gut-health', 'endometriosis', 'fibroids', 'hormonal-balance'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen recirculation and gut-liver detox axis',
  },
  {
    id: 'iodine',
    name: 'Iodine (Lugol\'s or Nascent)',
    category: 'Thyroid & Hormonal Support',
    subcategory: 'Minerals',
    description: 'Iodine deficiency is widespread and directly impacts thyroid function, ovarian health, and breast tissue — all of which influence pelvic floor function through hormonal pathways. The ovaries and uterus concentrate iodine, and deficiency has been linked to fibrocystic breast disease, ovarian cysts, and estrogen dominance. Supplementation should be guided by testing and started at low doses with cofactors including selenium, magnesium, and vitamin C.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/iodine.webp',
    tags: ['thyroid', 'iodine-deficiency', 'ovarian-health', 'estrogen-dominance', 'hormonal'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Thyroid and ovarian iodine support',
  },
  {
    id: 'selenium',
    name: 'Selenium (Selenomethionine)',
    category: 'Thyroid & Hormonal Support',
    subcategory: 'Minerals',
    description: 'Selenium is essential for thyroid hormone conversion (T4 to T3) and for the selenoprotein antioxidant enzymes including glutathione peroxidase that protect pelvic tissues from oxidative damage. Hashimoto\'s thyroiditis, which affects millions of women, is associated with pelvic floor dysfunction through hypothyroid effects on connective tissue, bladder function, and constipation. Selenomethionine is the most bioavailable form, and 200mcg daily has demonstrated reduction in thyroid antibodies in clinical trials.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/selenium.webp',
    tags: ['thyroid', 'Hashimotos', 'antioxidant', 'glutathione', 'hormonal'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Thyroid health and antioxidant protection',
  },
  {
    id: 'iron-bisglycinate',
    name: 'Iron Bisglycinate',
    category: 'Blood & Energy Support',
    subcategory: 'Minerals',
    description: 'Iron deficiency is the most common nutritional deficiency in women of reproductive age, contributing to fatigue, poor exercise tolerance, and impaired pelvic floor muscle recovery. Iron bisglycinate is the most gentle and well-absorbed form, causing significantly less constipation and gut irritation than ferrous sulfate. Adequate iron is essential for collagen synthesis, muscle oxygenation, and the energy production needed for pelvic floor rehabilitation.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/iron.webp',
    tags: ['iron-deficiency', 'anemia', 'fatigue', 'muscle-recovery', 'collagen'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Iron deficiency and muscle recovery',
  },
  {
    id: 'probiotics-vaginal',
    name: 'Vaginal Probiotic (Lactobacillus reuteri + rhamnosus)',
    category: 'Microbiome Support',
    subcategory: 'Vaginal Probiotics',
    description: 'The vaginal microbiome is dominated by Lactobacillus species that maintain an acidic pH protecting against bacterial vaginosis, yeast infections, and UTIs — all of which cause pelvic floor dysfunction through inflammation and pain. Oral supplementation with L. reuteri RC-14 and L. rhamnosus GR-1 has the strongest clinical evidence for colonizing the vaginal tract and reducing recurrent BV and UTIs. A healthy vaginal microbiome also supports comfortable intercourse and reduces vulvodynia.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/vaginal-probiotic.webp',
    tags: ['vaginal-microbiome', 'BV', 'UTI', 'yeast-infection', 'vulvodynia'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Vaginal microbiome and recurrent infections',
  },
  {
    id: 'boric-acid-suppositories',
    name: 'Boric Acid Suppositories',
    category: 'Microbiome Support',
    subcategory: 'Vaginal pH',
    description: 'Boric acid vaginal suppositories are a clinically validated treatment for recurrent bacterial vaginosis and vulvovaginal candidiasis, particularly azole-resistant Candida glabrata strains. The CDC includes boric acid in its BV treatment guidelines, and multiple studies confirm 70-80% efficacy for recurrent BV when used as maintenance therapy. By restoring vaginal pH and disrupting biofilm, they reduce the chronic inflammation that contributes to vulvodynia and pelvic floor dysfunction.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/boric-acid.webp',
    tags: ['BV', 'yeast-infection', 'vaginal-pH', 'recurrent-infections', 'vulvodynia'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Recurrent BV and vaginal pH restoration',
  },
  {
    id: 'prebiotic-fiber',
    name: 'Prebiotic Fiber (Partially Hydrolyzed Guar Gum)',
    category: 'Microbiome Support',
    subcategory: 'Gut Prebiotics',
    description: 'Prebiotic fiber feeds beneficial gut bacteria that produce short-chain fatty acids, regulate estrogen metabolism, and reduce systemic inflammation relevant to pelvic floor health. Partially hydrolyzed guar gum (PHGG) is particularly well-tolerated and has demonstrated efficacy for IBS-related constipation and diarrhea, both of which directly impact pelvic floor function. A healthy gut microbiome reduces the beta-glucuronidase activity that drives estrogen recirculation.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/prebiotic-fiber.webp',
    tags: ['gut-health', 'constipation', 'IBS', 'estrogen-metabolism', 'microbiome'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut microbiome and bowel regularity',
  },
  {
    id: 'zinc-carnosine',
    name: 'Zinc Carnosine',
    category: 'Gut & Mucosal Health',
    subcategory: 'Mucosal Protectants',
    description: 'Zinc carnosine is a chelated form of zinc and L-carnosine with demonstrated mucosal protective effects in the gut and urinary tract, relevant to leaky gut, intestinal permeability, and bladder lining integrity. Intestinal permeability is increasingly recognized as a driver of systemic inflammation in conditions like endometriosis, IC, and chronic pelvic pain. It supports tight junction integrity, reduces gut inflammation, and has been used clinically for gastric ulcers and intestinal permeability.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/zinc-carnosine.webp',
    tags: ['gut-health', 'leaky-gut', 'bladder-lining', 'endometriosis', 'IC'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Mucosal integrity and intestinal permeability',
  },
  {
    id: 'l-glutamine',
    name: 'L-Glutamine',
    category: 'Gut & Mucosal Health',
    subcategory: 'Amino Acids',
    description: 'L-glutamine is the primary fuel source for intestinal epithelial cells and is essential for maintaining gut barrier integrity, which is compromised in many women with chronic pelvic pain, endometriosis, and IBS. Clinical studies have demonstrated its ability to reduce intestinal permeability, decrease gut inflammation, and support mucosal healing. For pelvic floor health, a healthy gut barrier reduces the systemic inflammatory load that drives pelvic tissue inflammation and sensitization.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/l-glutamine.webp',
    tags: ['gut-health', 'leaky-gut', 'IBS', 'intestinal-permeability', 'anti-inflammatory'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut barrier integrity and mucosal healing',
  },
  {
    id: 'digestive-enzymes',
    name: 'Broad-Spectrum Digestive Enzymes',
    category: 'Gut & Mucosal Health',
    subcategory: 'Digestive Support',
    description: 'Digestive enzyme insufficiency contributes to incomplete protein digestion, gut inflammation, and food sensitivities that drive systemic inflammation relevant to pelvic floor conditions. Serrapeptase, a proteolytic enzyme, has demonstrated anti-inflammatory and fibrinolytic effects specifically relevant to endometriosis, adhesions, and scar tissue in the pelvis. Broad-spectrum enzymes support complete digestion and reduce the inflammatory burden from poorly digested proteins.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/digestive-enzymes.webp',
    tags: ['digestion', 'endometriosis', 'adhesions', 'inflammation', 'gut-health'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Digestive support and systemic inflammation',
  },
  {
    id: 'castor-oil-topical',
    name: 'Castor Oil (Topical / Packs)',
    category: 'Topical & External',
    subcategory: 'Lymphatic Support',
    description: 'Castor oil packs applied to the lower abdomen are a traditional naturopathic therapy for improving pelvic circulation, reducing inflammation, and supporting lymphatic drainage in the pelvis. Ricinoleic acid, castor oil\'s primary fatty acid, has demonstrated anti-inflammatory, analgesic, and lymphagogue effects in research. They are used for endometriosis, fibroids, pelvic adhesions, and constipation, and many women report significant pain reduction with consistent use.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/castor-oil.webp',
    tags: ['topical', 'endometriosis', 'fibroids', 'lymphatic', 'pelvic-circulation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Pelvic circulation and lymphatic drainage',
  },
  {
    id: 'topical-estrogen',
    name: 'Topical Estriol Cream (Rx)',
    category: 'Hormonal Topicals',
    subcategory: 'Vaginal Estrogen',
    description: 'Topical estriol (a weak estrogen) applied vaginally is the most evidence-based treatment for genitourinary syndrome of menopause (GSM), which includes vaginal atrophy, dryness, dyspareunia, and urinary urgency. Unlike systemic estrogen, vaginal estriol has minimal systemic absorption and is considered safe even for women with a history of hormone-sensitive cancers by many gynecologists. It restores vaginal epithelial thickness, normalizes vaginal pH, and reduces the urinary symptoms that accompany pelvic floor changes in menopause.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/topical-estrogen.webp',
    tags: ['menopause', 'vaginal-atrophy', 'dyspareunia', 'GSM', 'urinary-urgency'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Vaginal atrophy and genitourinary syndrome of menopause',
  },
  {
    id: 'dhea-topical',
    name: 'Topical DHEA (Intrarosa)',
    category: 'Hormonal Topicals',
    subcategory: 'Vaginal Androgens',
    description: 'Topical DHEA (prasterone) is FDA-approved for dyspareunia due to menopause and works by converting locally to both estrogen and testosterone in vaginal tissues, restoring tissue health without significant systemic hormone exposure. It addresses the androgen component of vaginal atrophy that estrogen alone doesn\'t fully treat, including clitoral sensitivity, libido, and vaginal tissue thickness. It is an option for women who cannot or prefer not to use estrogen.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/dhea-topical.webp',
    tags: ['menopause', 'dyspareunia', 'libido', 'vaginal-atrophy', 'DHEA'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Dyspareunia and vaginal androgen deficiency',
  },
  {
    id: 'hemp-cbd',
    name: 'CBD (Cannabidiol)',
    category: 'Pain & Nervous System',
    subcategory: 'Cannabinoids',
    description: 'CBD interacts with the endocannabinoid system, which plays a significant role in pelvic pain modulation, bladder function, and nervous system regulation relevant to pelvic floor dysfunction. Emerging research suggests CBD may reduce central sensitization, bladder hyperactivity, and pelvic muscle tension through its effects on CB1 and CB2 receptors and TRPV1 channels. It is being studied for endometriosis, IC, and vulvodynia with promising preliminary results.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/cbd.webp',
    tags: ['pain', 'endocannabinoid', 'bladder', 'central-sensitization', 'vulvodynia'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Pelvic pain and nervous system regulation',
  },
  {
    id: 'passionflower',
    name: 'Passionflower (Passiflora incarnata)',
    category: 'Pain & Nervous System',
    subcategory: 'Nervines',
    description: 'Passionflower is a gentle anxiolytic and nervine sedative with clinical evidence for anxiety, insomnia, and nervous system hyperactivation — all of which maintain pelvic floor hypertonicity. A clinical trial found it comparable to oxazepam for generalized anxiety disorder, without the dependency risk. For pelvic floor health, its ability to reduce sympathetic nervous system dominance supports pelvic muscle relaxation and pain reduction.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/passionflower.webp',
    tags: ['anxiety', 'nervine', 'hypertonic-pelvic-floor', 'sleep', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Anxiety and nervous system hyperactivation',
  },
  {
    id: 'valerian',
    name: 'Valerian Root',
    category: 'Pain & Nervous System',
    subcategory: 'Nervines',
    description: 'Valerian root is a traditional sedative and nervine herb with GABAergic mechanisms that reduce anxiety, improve sleep quality, and relax smooth and skeletal muscle. Poor sleep is a significant driver of pelvic floor dysfunction through its effects on pain sensitivity, cortisol regulation, and tissue repair. It is particularly useful for women whose pelvic floor tension worsens at night or is associated with sleep disturbance and anxiety.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/valerian.webp',
    tags: ['sleep', 'anxiety', 'GABA', 'muscle-relaxant', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Sleep quality and nervous system relaxation',
  },
  {
    id: 'lions-mane',
    name: 'Lion\'s Mane Mushroom',
    category: 'Nervous System Support',
    subcategory: 'Nootropics',
    description: 'Lion\'s mane contains hericenones and erinacines that stimulate nerve growth factor (NGF) production, supporting nerve repair and regeneration relevant to pudendal neuralgia, pelvic nerve damage, and post-surgical nerve recovery. Pudendal nerve dysfunction is a common and underdiagnosed cause of chronic pelvic pain, and supporting nerve health through NGF stimulation may aid recovery. It also has anti-inflammatory and gut-supportive properties.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/lions-mane.webp',
    tags: ['nerve-repair', 'pudendal-neuralgia', 'NGF', 'neuropathy', 'mushroom'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Nerve repair and pudendal neuralgia',
  },
  {
    id: 'reishi',
    name: 'Reishi Mushroom (Ganoderma lucidum)',
    category: 'Nervous System Support',
    subcategory: 'Adaptogens',
    description: 'Reishi is an adaptogenic mushroom used in TCM for over 2,000 years for its immune-modulating, anti-inflammatory, and nervous system calming properties. Its triterpenes and beta-glucans reduce inflammatory cytokines relevant to autoimmune pelvic conditions, endometriosis, and IC. It is particularly valued for its ability to calm the nervous system and support sleep without sedation, addressing the anxiety-pelvic floor tension cycle.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/reishi.webp',
    tags: ['adaptogen', 'immune-modulation', 'endometriosis', 'anxiety', 'sleep'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Immune modulation and nervous system calm',
  },
  {
    id: 'cordyceps',
    name: 'Cordyceps Mushroom',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Cordyceps is an adaptogenic mushroom that supports adrenal function, mitochondrial energy production, and oxygen utilization — all relevant to pelvic floor rehabilitation and recovery from chronic fatigue associated with pelvic conditions. It increases ATP production in muscle cells and has demonstrated improvements in exercise capacity and recovery in clinical trials. For women with pelvic floor dysfunction complicated by chronic fatigue or adrenal exhaustion, it supports the energy needed for rehabilitation.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/cordyceps.webp',
    tags: ['adaptogen', 'adrenal', 'energy', 'exercise-recovery', 'mitochondria'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Energy production and adrenal support',
  },
  {
    id: 'rhodiola',
    name: 'Rhodiola Rosea',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Rhodiola is a Scandinavian adaptogen with strong clinical evidence for reducing fatigue, burnout, and stress-related exhaustion that commonly accompanies chronic pelvic pain conditions. Its rosavins and salidroside regulate cortisol, support HPA axis function, and improve stress resilience. For women with pelvic floor dysfunction driven by chronic stress and nervous system dysregulation, rhodiola addresses the upstream cause rather than just the symptoms.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/rhodiola.webp',
    tags: ['adaptogen', 'fatigue', 'cortisol', 'HPA-axis', 'stress'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Fatigue and stress-related adrenal exhaustion',
  },
  {
    id: 'holy-basil',
    name: 'Holy Basil / Tulsi (Ocimum tenuiflorum)',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Holy basil (tulsi) is a sacred Ayurvedic adaptogen with cortisol-lowering, anti-inflammatory, and blood sugar-regulating properties relevant to stress-driven pelvic floor dysfunction and PCOS. Clinical trials have demonstrated its ability to reduce cortisol, fasting glucose, and anxiety, addressing the metabolic and stress components of pelvic conditions. It is particularly valued for its gentle, cumulative effect on the nervous system and its safety for long-term use.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/holy-basil.webp',
    tags: ['adaptogen', 'cortisol', 'PCOS', 'blood-sugar', 'Ayurveda'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Cortisol regulation and PCOS support',
  },
  {
    id: 'maca',
    name: 'Maca Root (Lepidium meyenii)',
    category: 'Hormonal Balance',
    subcategory: 'Endocrine Adaptogens',
    description: 'Maca is a Peruvian root vegetable with adaptogenic effects on the endocrine system, supporting hormonal balance without containing phytoestrogens or directly affecting hormone levels. Clinical trials have demonstrated improvements in menopausal symptoms, libido, and sexual function in postmenopausal women. For pelvic floor health, its support of sexual function, energy, and hormonal balance makes it relevant for women experiencing pelvic floor dysfunction alongside hormonal transitions.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/maca.webp',
    tags: ['hormonal-balance', 'menopause', 'libido', 'sexual-function', 'adaptogen'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Hormonal balance and sexual function',
  },
  {
    id: 'evening-primrose',
    name: 'Evening Primrose Oil',
    category: 'Essential Fatty Acids',
    subcategory: 'GLA Sources',
    description: 'Evening primrose oil is rich in gamma-linolenic acid (GLA), an omega-6 fatty acid that reduces inflammatory prostaglandins relevant to menstrual pain, endometriosis, and pelvic inflammation. It is particularly effective for PMS-related breast tenderness, mood symptoms, and dysmenorrhea when taken throughout the menstrual cycle. GLA also supports skin and mucosal membrane health, which is relevant to vaginal tissue integrity and comfort.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/evening-primrose.webp',
    tags: ['GLA', 'PMS', 'dysmenorrhea', 'endometriosis', 'mucosal-health'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'PMS and prostaglandin-driven pelvic pain',
  },
  {
    id: 'black-seed-oil',
    name: 'Black Seed Oil (Nigella sativa)',
    category: 'Anti-Inflammatory',
    subcategory: 'Seed Oils',
    description: 'Black seed oil contains thymoquinone, one of the most potent natural anti-inflammatory and immunomodulatory compounds, with demonstrated efficacy for autoimmune conditions, endometriosis, and chronic inflammatory pain. Multiple studies have shown its ability to reduce inflammatory cytokines, modulate immune function, and reduce pain in conditions relevant to pelvic floor health. It is used in both Islamic medicine and modern integrative practice for endometriosis, PCOS, and chronic pelvic inflammation.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/black-seed-oil.webp',
    tags: ['anti-inflammatory', 'endometriosis', 'autoimmune', 'PCOS', 'thymoquinone'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Autoimmune inflammation and endometriosis',
  },
  {
    id: 'serrapeptase',
    name: 'Serrapeptase',
    category: 'Systemic Enzymes',
    subcategory: 'Proteolytic Enzymes',
    description: 'Serrapeptase is a proteolytic enzyme derived from silkworm bacteria with demonstrated anti-inflammatory, fibrinolytic, and scar-dissolving properties relevant to endometriosis adhesions, post-surgical scar tissue, and pelvic fibrosis. It breaks down non-living tissue including fibrin, scar tissue, and inflammatory proteins without affecting living tissue. Clinical studies have shown its efficacy for reducing post-surgical adhesions and chronic inflammatory conditions.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/serrapeptase.webp',
    tags: ['endometriosis', 'adhesions', 'scar-tissue', 'anti-inflammatory', 'fibrinolytic'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Adhesions and scar tissue dissolution',
  },
  {
    id: 'nattokinase',
    name: 'Nattokinase',
    category: 'Systemic Enzymes',
    subcategory: 'Fibrinolytic Enzymes',
    description: 'Nattokinase is a fibrinolytic enzyme from fermented soybeans (natto) that dissolves fibrin clots and supports healthy blood viscosity, with relevance to pelvic congestion syndrome, endometriosis, and conditions involving poor pelvic circulation. It has demonstrated cardiovascular and anti-thrombotic effects in clinical research, and is used in integrative medicine for conditions involving fibrin accumulation in pelvic tissues. It works synergistically with serrapeptase for adhesion and scar tissue management.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/nattokinase.webp',
    tags: ['fibrinolytic', 'pelvic-congestion', 'endometriosis', 'circulation', 'adhesions'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Fibrin dissolution and pelvic circulation',
  },
  {
    id: 'wobenzym',
    name: 'Wobenzym (Systemic Enzyme Blend)',
    category: 'Systemic Enzymes',
    subcategory: 'Enzyme Blends',
    description: 'Wobenzym is a German systemic enzyme formula combining pancreatin, bromelain, papain, trypsin, chymotrypsin, and rutin with extensive clinical research for inflammatory conditions, post-surgical recovery, and autoimmune diseases. Its anti-inflammatory effects are comparable to NSAIDs in some studies without the gastrointestinal side effects, making it relevant for chronic pelvic pain management. It is widely used in European integrative medicine for endometriosis, pelvic inflammatory disease, and post-surgical adhesion prevention.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/wobenzym.webp',
    tags: ['systemic-enzymes', 'endometriosis', 'post-surgical', 'anti-inflammatory', 'autoimmune'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Systemic inflammation and post-surgical recovery',
  },
  {
    id: 'boswellia',
    name: 'Boswellia (Frankincense)',
    category: 'Anti-Inflammatory',
    subcategory: 'Resins',
    description: 'Boswellia serrata contains boswellic acids that specifically inhibit 5-LOX (5-lipoxygenase), an inflammatory enzyme pathway not targeted by NSAIDs, making it complementary to conventional anti-inflammatory approaches for endometriosis and chronic pelvic pain. Clinical trials have demonstrated its efficacy for inflammatory bowel disease, arthritis, and asthma, with emerging research for endometriosis and pelvic inflammation. AKBA (acetyl-11-keto-beta-boswellic acid) is the most potent anti-inflammatory compound.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/boswellia.webp',
    tags: ['anti-inflammatory', 'endometriosis', '5-LOX', 'chronic-pain', 'frankincense'],
    evidenceLevel: 'moderate',
    primaryBenefit: '5-LOX inflammation and endometriosis pain',
  },
  {
    id: 'cats-claw',
    name: 'Cat\'s Claw (Uncaria tomentosa)',
    category: 'Anti-Inflammatory',
    subcategory: 'Bark Extracts',
    description: 'Cat\'s claw is a South American herb with potent anti-inflammatory, immunomodulatory, and DNA-repair properties, used for autoimmune conditions, chronic inflammatory pain, and conditions involving NF-kB-driven inflammation. Its oxindole alkaloids modulate immune function and reduce inflammatory cytokines relevant to endometriosis, IC, and chronic pelvic pain syndrome. It is used in integrative oncology and for conditions involving chronic immune activation.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/cats-claw.webp',
    tags: ['anti-inflammatory', 'autoimmune', 'endometriosis', 'IC', 'NF-kB'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Autoimmune inflammation and chronic pelvic pain',
  },
  {
    id: 'pine-pollen',
    name: 'Pine Pollen',
    category: 'Hormonal Balance',
    subcategory: 'Phytoandrogens',
    description: 'Pine pollen contains phytoandrogens including testosterone, DHEA, and androstenedione in small amounts, along with brassinosteroids that may support androgen levels in women with low testosterone contributing to low libido, fatigue, and reduced pelvic floor muscle tone. It is used in Chinese medicine and Western herbalism for conditions involving androgen deficiency, including postmenopausal sexual dysfunction and adrenal fatigue. The tincture form provides better absorption of the androgenic compounds than powder.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/pine-pollen.webp',
    tags: ['androgens', 'libido', 'testosterone', 'menopause', 'adrenal'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Androgen support and libido',
  },
'''

# Read the file
with open('/home/ubuntu/the-pelvic-floor/src/data/supplements.ts', 'r') as f:
    content = f.read()

# Find the closing of the array and insert before it
# The file ends with "];\nexport default supplements;\n"
iinsert_before = '];

export default supplements;'

if insert_before in content:
    new_content = content.replace(insert_before, NEW_SUPPLEMENTS + '\n' + insert_before)
    with open('/home/ubuntu/the-pelvic-floor/src/data/supplements.ts', 'w') as f:
        f.write(new_content)
    print("SUCCESS: Supplements appended")
    # Count entries
    import re
    count = len(re.findall(r"^\s+id:", new_content, re.MULTILINE))
    print(f"Total supplement entries: {count}")
else:
    print("ERROR: Could not find insertion point")
    print("Last 100 chars:", repr(content[-100:]))
