#!/usr/bin/env python3
"""Append 40 more unique supplement entries to reach 200+."""
import re

NEW_ENTRIES = """
  // ─── ADDITIONAL WESTERN HERBS ─────────────────────────────────────────────
  {
    id: 'ginger-root',
    name: 'Ginger Root (Zingiber officinale)',
    category: 'Anti-Inflammatory',
    subcategory: 'Digestive Anti-Inflammatories',
    description: 'Ginger contains gingerols and shogaols that inhibit COX-2 and 5-LOX inflammatory pathways, with clinical evidence for dysmenorrhea comparable to ibuprofen in some trials. It also supports digestive function, reduces nausea, and improves pelvic circulation through its vasodilatory effects. For pelvic floor health, its dual action on inflammation and digestion makes it relevant for menstrual pain, endometriosis, and IBS-related pelvic dysfunction.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/ginger.webp',
    tags: ['anti-inflammatory', 'dysmenorrhea', 'digestive', 'COX-2', 'pelvic-circulation'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Dysmenorrhea and digestive anti-inflammatory',
  },
  {
    id: 'turmeric-curcumin',
    name: 'Turmeric / Curcumin (BCM-95)',
    category: 'Anti-Inflammatory',
    subcategory: 'Polyphenols',
    description: 'Curcumin is the most studied natural anti-inflammatory compound, with extensive evidence for reducing NF-kB-driven inflammation relevant to endometriosis, PCOS, and chronic pelvic pain. BCM-95 (biocurcumin) is the most bioavailable form, with 7x better absorption than standard curcumin. Multiple clinical trials have demonstrated its efficacy for endometriosis pain, with mechanisms including reduction of prostaglandins, inflammatory cytokines, and angiogenesis in endometrial lesions.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/curcumin.webp',
    tags: ['anti-inflammatory', 'endometriosis', 'PCOS', 'NF-kB', 'chronic-pain'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Endometriosis and systemic inflammation',
  },
  {
    id: 'licorice-root-dgl',
    name: 'Licorice Root (DGL)',
    category: 'Hormonal Balance',
    subcategory: 'Adrenal Tonics',
    description: 'Deglycyrrhizinated licorice (DGL) supports adrenal function and cortisol regulation without the blood pressure-raising effects of whole licorice, making it relevant for HPA axis dysregulation that drives stress-related pelvic floor dysfunction. Glycyrrhizin in whole licorice also has phytoestrogenic and anti-androgenic effects used in TCM and Ayurveda for PCOS and androgen excess. The combination of white peony root and licorice (Shao Yao Gan Cao Tang) is specifically used for pelvic muscle spasm and vaginismus.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/licorice.webp',
    tags: ['adrenal', 'cortisol', 'PCOS', 'vaginismus', 'HPA-axis'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Adrenal support and PCOS',
  },
  {
    id: 'nettle-leaf',
    name: 'Stinging Nettle Leaf',
    category: 'Urinary & Hormonal Support',
    subcategory: 'Nutritive Herbs',
    description: 'Stinging nettle leaf is one of the most nutritionally dense herbs, providing bioavailable iron, calcium, magnesium, and vitamin K that support pelvic floor muscle function and connective tissue integrity. It has demonstrated anti-inflammatory, antihistamine, and diuretic effects relevant to bladder irritability and pelvic inflammation. Nettle root (distinct from leaf) inhibits sex hormone binding globulin (SHBG), potentially increasing free testosterone and estrogen availability.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/nettle.webp',
    tags: ['nutritive', 'iron', 'bladder', 'anti-inflammatory', 'hormonal'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Nutritional support and bladder health',
  },
  {
    id: 'dandelion-root',
    name: 'Dandelion Root',
    category: 'Liver & Detox Support',
    subcategory: 'Hepatics',
    description: 'Dandelion root is a gentle liver tonic and cholagogue that supports bile production and flow, which is essential for estrogen conjugation and excretion through the gut-liver axis. Impaired liver function and bile flow contribute to estrogen recirculation and dominance, driving endometriosis, fibroids, and hormonal pelvic pain. It also has prebiotic inulin content that supports beneficial gut bacteria involved in estrogen metabolism.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/dandelion.webp',
    tags: ['liver', 'estrogen-detox', 'bile', 'gut-health', 'hormonal-balance'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Liver support and estrogen detoxification',
  },
  {
    id: 'wild-yam-root',
    name: 'Wild Yam Root (Dioscorea villosa)',
    category: 'Hormonal Balance',
    subcategory: 'Phytoprogestins',
    description: 'Wild yam contains diosgenin, a steroidal saponin that is a laboratory precursor to progesterone, and is used in herbal medicine for progesterone deficiency patterns including PMS, luteal phase deficiency, and perimenopausal pelvic floor changes. Topical wild yam creams are widely used for menopausal symptoms, though the human body cannot directly convert diosgenin to progesterone without laboratory processing. It is most effective as part of a comprehensive hormonal support protocol.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/wild-yam.webp',
    tags: ['progesterone', 'menopause', 'PMS', 'hormonal-balance', 'Western-herbs'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Progesterone support and hormonal balance',
  },
  {
    id: 'ladies-mantle',
    name: "Lady's Mantle (Alchemilla vulgaris)",
    category: 'Uterine & Pelvic Tonics',
    subcategory: 'Uterine Astringents',
    description: "Lady's mantle is a traditional European herb for women's reproductive health, used as a uterine astringent for heavy periods, vaginal discharge, and pelvic organ prolapse. Its tannins tone and tighten pelvic tissues, while its progesterogenic effects support the luteal phase and reduce estrogen dominance patterns. It is often combined with shepherd's purse for heavy bleeding and with cramp bark for dysmenorrhea.",
    asin: 'B00014GKRE',
    imageKey: 'supplements/ladys-mantle.webp',
    tags: ['uterine-tonic', 'prolapse', 'heavy-periods', 'progesterone', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine astringency and pelvic tissue tone',
  },
  {
    id: 'goldenrod-herb',
    name: 'Goldenrod (Solidago virgaurea)',
    category: 'Bladder & Urinary Health',
    subcategory: 'Urinary Tonics',
    description: 'Goldenrod is a European urinary tonic with anti-inflammatory, antispasmodic, and mild diuretic properties used for bladder inflammation, kidney stones, and urinary tract infections. Clinical studies have confirmed its efficacy for reducing bladder inflammation and supporting urinary tract health. It is particularly useful for the type of bladder irritability that accompanies interstitial cystitis and pelvic floor hypertonicity.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/goldenrod.webp',
    tags: ['urinary-tonic', 'bladder-inflammation', 'interstitial-cystitis', 'kidney-stones', 'Western-herbs'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bladder inflammation and urinary tract health',
  },
  {
    id: 'cats-claw-herb',
    name: "Cat's Claw (Uncaria tomentosa)",
    category: 'Anti-Inflammatory',
    subcategory: 'Bark Extracts',
    description: "Cat's claw is a South American herb with potent anti-inflammatory, immunomodulatory, and DNA-repair properties, used for autoimmune conditions, chronic inflammatory pain, and conditions involving NF-kB-driven inflammation. Its oxindole alkaloids modulate immune function and reduce inflammatory cytokines relevant to endometriosis, IC, and chronic pelvic pain syndrome. It is used in integrative oncology and for conditions involving chronic immune activation.",
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/cats-claw.webp',
    tags: ['anti-inflammatory', 'autoimmune', 'endometriosis', 'IC', 'NF-kB'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Autoimmune inflammation and chronic pelvic pain',
  },
  {
    id: 'pine-pollen-tincture',
    name: 'Pine Pollen Tincture',
    category: 'Hormonal Balance',
    subcategory: 'Phytoandrogens',
    description: 'Pine pollen tincture contains phytoandrogens including testosterone, DHEA, and androstenedione in small amounts, along with brassinosteroids that may support androgen levels in women with low testosterone contributing to low libido, fatigue, and reduced pelvic floor muscle tone. It is used in Chinese medicine and Western herbalism for conditions involving androgen deficiency, including postmenopausal sexual dysfunction and adrenal fatigue. The tincture form provides better absorption of the androgenic compounds than powder.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/pine-pollen.webp',
    tags: ['androgens', 'libido', 'testosterone', 'menopause', 'adrenal'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Androgen support and libido',
  },
  // ─── TRACE MINERALS & VITAMINS ────────────────────────────────────────────
  {
    id: 'iron-bisglycinate-chelate',
    name: 'Iron Bisglycinate Chelate',
    category: 'Blood & Energy Support',
    subcategory: 'Minerals',
    description: 'Iron deficiency is the most common nutritional deficiency in women of reproductive age, contributing to fatigue, poor exercise tolerance, and impaired pelvic floor muscle recovery. Iron bisglycinate chelate is the most gentle and well-absorbed form, causing significantly less constipation and gut irritation than ferrous sulfate. Adequate iron is essential for collagen synthesis, muscle oxygenation, and the energy production needed for pelvic floor rehabilitation.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/iron.webp',
    tags: ['iron-deficiency', 'anemia', 'fatigue', 'muscle-recovery', 'collagen'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Iron deficiency and muscle recovery',
  },
  {
    id: 'vitamin-k2-mk7',
    name: 'Vitamin K2 (MK-7)',
    category: 'Bone & Connective Tissue',
    subcategory: 'Fat-Soluble Vitamins',
    description: 'Vitamin K2 activates matrix Gla protein (MGP), which prevents calcium deposition in soft tissues and directs it to bones and teeth, supporting the integrity of pelvic ligaments and fascia. For pelvic floor health, K2 is relevant to pelvic ligament and fascia integrity, as calcification of pelvic ligaments contributes to rigidity and pain. It works synergistically with vitamin D3 and magnesium for comprehensive pelvic connective tissue support.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/vitamin-k2.webp',
    tags: ['bone-health', 'connective-tissue', 'calcium-metabolism', 'pelvic-ligaments', 'vitamin-D'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue integrity and calcium metabolism',
  },
  {
    id: 'vitamin-a-retinol',
    name: 'Vitamin A (Retinol)',
    category: 'Mucosal Health',
    subcategory: 'Fat-Soluble Vitamins',
    description: 'Vitamin A (retinol) is essential for the maintenance of mucosal epithelial tissues throughout the body, including the vaginal epithelium, bladder lining, and intestinal mucosa. Deficiency contributes to vaginal atrophy, increased susceptibility to infections, and impaired mucosal healing. It works synergistically with zinc and vitamin C for comprehensive mucosal tissue support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/vitamin-a.webp',
    tags: ['mucosal-health', 'vaginal-epithelium', 'bladder-lining', 'immune', 'tissue-repair'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Mucosal tissue health and vaginal epithelium',
  },
  {
    id: 'zinc-bisglycinate',
    name: 'Zinc Bisglycinate',
    category: 'Immune & Reproductive Health',
    subcategory: 'Minerals',
    description: 'Zinc is essential for immune function, wound healing, collagen synthesis, and reproductive hormone production, all of which are relevant to pelvic floor health. It is required for the activity of over 300 enzymes including those involved in tissue repair, estrogen metabolism, and progesterone synthesis. Zinc deficiency is common in women with heavy periods, vegetarians, and those on oral contraceptives, and contributes to impaired healing and hormonal imbalance.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/zinc.webp',
    tags: ['immune', 'wound-healing', 'collagen', 'hormonal-balance', 'reproductive-health'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Immune function and reproductive hormone support',
  },
  {
    id: 'copper-bisglycinate',
    name: 'Copper Bisglycinate',
    category: 'Connective Tissue Support',
    subcategory: 'Minerals',
    description: 'Copper is a cofactor for lysyl oxidase, the enzyme that cross-links collagen and elastin fibers in connective tissue, making it essential for the tensile strength of pelvic floor fascia and ligaments. Copper deficiency, which can be induced by excess zinc supplementation, contributes to connective tissue weakness and laxity. It is best supplemented in a balanced ratio with zinc (approximately 1mg copper per 10-15mg zinc).',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/copper.webp',
    tags: ['connective-tissue', 'collagen', 'elastin', 'pelvic-ligaments', 'zinc-balance'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue cross-linking and pelvic ligament strength',
  },
  {
    id: 'boron-glycinate',
    name: 'Boron (Glycinate)',
    category: 'Hormonal Balance',
    subcategory: 'Trace Minerals',
    description: 'Boron is a trace mineral that supports estrogen and testosterone metabolism, bone density, and cognitive function, with research showing it increases serum estradiol and testosterone levels. It reduces inflammatory cytokines and improves magnesium absorption, making it a valuable addition to pelvic floor health protocols. For perimenopausal and menopausal women, its hormonal support is relevant to maintaining tissue integrity and reducing pelvic floor changes.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/boron.webp',
    tags: ['hormonal-balance', 'estrogen', 'testosterone', 'bone-density', 'menopause'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Hormonal support and bone density',
  },
  {
    id: 'silica-osa',
    name: 'Silica (Orthosilicic Acid)',
    category: 'Connective Tissue Support',
    subcategory: 'Minerals',
    description: 'Silica is essential for collagen synthesis and the structural integrity of connective tissues, skin, hair, and nails, with orthosilicic acid (OSA) being the most bioavailable form. Clinical studies have demonstrated OSA\'s ability to increase collagen synthesis and improve skin elasticity, with direct relevance to pelvic floor fascia and ligament strength. For pelvic floor health, adequate silica supports the tensile strength of the connective tissues that hold pelvic organs in place.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/silica.webp',
    tags: ['connective-tissue', 'collagen', 'pelvic-fascia', 'ligaments', 'tissue-strength'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue strength and collagen synthesis',
  },
  // ─── SPECIALIZED COMPOUNDS ────────────────────────────────────────────────
  {
    id: 'prebiotic-phgg',
    name: 'Prebiotic Fiber (PHGG)',
    category: 'Microbiome Support',
    subcategory: 'Gut Prebiotics',
    description: 'Partially hydrolyzed guar gum (PHGG) is a prebiotic fiber that feeds beneficial gut bacteria producing short-chain fatty acids, regulating estrogen metabolism, and reducing systemic inflammation relevant to pelvic floor health. It is particularly well-tolerated and has demonstrated efficacy for IBS-related constipation and diarrhea, both of which directly impact pelvic floor function. A healthy gut microbiome reduces the beta-glucuronidase activity that drives estrogen recirculation.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/prebiotic-fiber.webp',
    tags: ['gut-health', 'constipation', 'IBS', 'estrogen-metabolism', 'microbiome'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut microbiome and bowel regularity',
  },
  {
    id: 'l-glutamine-gut',
    name: 'L-Glutamine (Gut Support)',
    category: 'Gut & Mucosal Health',
    subcategory: 'Amino Acids',
    description: 'L-glutamine is the primary fuel source for intestinal epithelial cells and is essential for maintaining gut barrier integrity, which is compromised in many women with chronic pelvic pain, endometriosis, and IBS. Clinical studies have demonstrated its ability to reduce intestinal permeability, decrease gut inflammation, and support mucosal healing. For pelvic floor health, a healthy gut barrier reduces the systemic inflammatory load that drives pelvic tissue inflammation and sensitization.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/l-glutamine.webp',
    tags: ['gut-health', 'leaky-gut', 'IBS', 'intestinal-permeability', 'anti-inflammatory'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut barrier integrity and mucosal healing',
  },
  {
    id: 'zinc-carnosine-gut',
    name: 'Zinc Carnosine',
    category: 'Gut & Mucosal Health',
    subcategory: 'Mucosal Protectants',
    description: 'Zinc carnosine is a chelated form of zinc and L-carnosine with demonstrated mucosal protective effects in the gut and urinary tract, relevant to leaky gut, intestinal permeability, and bladder lining integrity. Intestinal permeability is increasingly recognized as a driver of systemic inflammation in conditions like endometriosis, IC, and chronic pelvic pain. It supports tight junction integrity, reduces gut inflammation, and has been used clinically for gastric ulcers and intestinal permeability.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/zinc-carnosine.webp',
    tags: ['gut-health', 'leaky-gut', 'bladder-lining', 'endometriosis', 'IC'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Mucosal integrity and intestinal permeability',
  },
  {
    id: 'hemp-cbd-oil',
    name: 'CBD Oil (Cannabidiol)',
    category: 'Pain & Nervous System',
    subcategory: 'Cannabinoids',
    description: 'CBD interacts with the endocannabinoid system, which plays a significant role in pelvic pain modulation, bladder function, and nervous system regulation relevant to pelvic floor dysfunction. Emerging research suggests CBD may reduce central sensitization, bladder hyperactivity, and pelvic muscle tension through its effects on CB1 and CB2 receptors and TRPV1 channels. It is being studied for endometriosis, IC, and vulvodynia with promising preliminary results.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/cbd.webp',
    tags: ['pain', 'endocannabinoid', 'bladder', 'central-sensitization', 'vulvodynia'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Pelvic pain and nervous system regulation',
  },
  {
    id: 'castor-oil-topical',
    name: 'Castor Oil (Topical Packs)',
    category: 'Topical & External',
    subcategory: 'Lymphatic Support',
    description: "Castor oil packs applied to the lower abdomen are a traditional naturopathic therapy for improving pelvic circulation, reducing inflammation, and supporting lymphatic drainage in the pelvis. Ricinoleic acid, castor oil's primary fatty acid, has demonstrated anti-inflammatory, analgesic, and lymphagogue effects in research. They are used for endometriosis, fibroids, pelvic adhesions, and constipation, and many women report significant pain reduction with consistent use.",
    asin: 'B00014GKRE',
    imageKey: 'supplements/castor-oil.webp',
    tags: ['topical', 'endometriosis', 'fibroids', 'lymphatic', 'pelvic-circulation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Pelvic circulation and lymphatic drainage',
  },
  {
    id: 'wobenzym-enzymes',
    name: 'Wobenzym (Systemic Enzyme Blend)',
    category: 'Systemic Enzymes',
    subcategory: 'Enzyme Blends',
    description: 'Wobenzym is a German systemic enzyme formula combining pancreatin, bromelain, papain, trypsin, chymotrypsin, and rutin with extensive clinical research for inflammatory conditions, post-surgical recovery, and autoimmune diseases. Its anti-inflammatory effects are comparable to NSAIDs in some studies without the gastrointestinal side effects, making it relevant for chronic pelvic pain management. It is widely used in European integrative medicine for endometriosis, pelvic inflammatory disease, and post-surgical adhesion prevention.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/wobenzym.webp',
    tags: ['systemic-enzymes', 'endometriosis', 'post-surgical', 'anti-inflammatory', 'autoimmune'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Systemic inflammation and post-surgical recovery',
  },
  {
    id: 'sulforaphane-broccoli',
    name: 'Sulforaphane (Broccoli Sprout Extract)',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Metabolism',
    description: 'Sulforaphane activates the Nrf2 pathway, the master regulator of antioxidant and detoxification genes, and supports phase 2 liver detoxification of estrogens and other hormones. It has demonstrated anti-cancer, anti-inflammatory, and estrogen-modulating effects in research, making it relevant for estrogen-driven conditions like endometriosis, fibroids, and hormonal pelvic pain. It works synergistically with DIM and calcium D-glucarate for comprehensive estrogen metabolism support.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/sulforaphane.webp',
    tags: ['estrogen-metabolism', 'Nrf2', 'endometriosis', 'fibroids', 'detox'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen detoxification and Nrf2 activation',
  },
  {
    id: 'ala-neuropathy',
    name: 'Alpha Lipoic Acid (ALA)',
    category: 'Anti-Inflammatory',
    subcategory: 'Antioxidants',
    description: 'Alpha lipoic acid is a universal antioxidant that works in both fat-soluble and water-soluble environments, regenerates other antioxidants including vitamins C and E and glutathione, and has demonstrated neuroprotective effects relevant to pudendal neuralgia and pelvic nerve pain. Clinical studies have shown its efficacy for diabetic neuropathy, and it is used in integrative medicine for neuropathic pelvic pain conditions. It also has anti-inflammatory effects on NF-kB pathways relevant to chronic pelvic inflammation.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/ala.webp',
    tags: ['neuropathy', 'pudendal-neuralgia', 'antioxidant', 'nerve-pain', 'anti-inflammatory'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Neuropathic pain and antioxidant support',
  },
  {
    id: 'coq10-ubiquinol',
    name: 'CoQ10 Ubiquinol (200mg)',
    category: 'Energy & Mitochondrial Support',
    subcategory: 'Mitochondrial Nutrients',
    description: 'CoQ10 as ubiquinol (the active, reduced form) is essential for mitochondrial energy production in all cells including pelvic floor muscles, and has demonstrated anti-inflammatory, antioxidant, and fertility-supporting effects. It is particularly relevant for women with endometriosis, where mitochondrial dysfunction and oxidative stress in pelvic tissues contribute to pain and infertility. Ubiquinol is 3-8x more bioavailable than ubiquinone and is the preferred form for women over 40.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/coq10-ubiquinol.webp',
    tags: ['mitochondria', 'energy', 'endometriosis', 'fertility', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Mitochondrial energy and endometriosis support',
  },
  {
    id: 'phosphatidylserine-cortisol',
    name: 'Phosphatidylserine',
    category: 'Nervous System Support',
    subcategory: 'Phospholipids',
    description: 'Phosphatidylserine is a phospholipid essential for neuronal membrane integrity and has demonstrated the ability to reduce cortisol response to exercise and psychological stress, making it relevant for women with stress-driven pelvic floor dysfunction. Elevated cortisol maintains sympathetic nervous system dominance that prevents pelvic floor relaxation and healing. It is used in integrative medicine for HPA axis dysregulation, adrenal fatigue, and stress-related conditions.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/phosphatidylserine.webp',
    tags: ['cortisol', 'HPA-axis', 'stress', 'nervous-system', 'adrenal'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Cortisol regulation and HPA axis support',
  },
  {
    id: 'gaba-pelvic',
    name: 'GABA (PharmaGABA)',
    category: 'Nervous System Support',
    subcategory: 'Neurotransmitters',
    description: 'GABA is the primary inhibitory neurotransmitter that reduces neuronal excitability and promotes relaxation throughout the nervous system, including the pudendal nerve pathways that innervate the pelvic floor. PharmaGABA (naturally fermented GABA) has demonstrated anxiolytic and muscle-relaxing effects in clinical studies. For women with hypertonic pelvic floor conditions driven by nervous system hyperactivation, GABA support may reduce the baseline tension that prevents healing.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/gaba.webp',
    tags: ['GABA', 'anxiety', 'hypertonic-pelvic-floor', 'nervous-system', 'muscle-relaxant'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Nervous system inhibition and pelvic floor relaxation',
  },
  {
    id: 'l-theanine-calm',
    name: 'L-Theanine',
    category: 'Nervous System Support',
    subcategory: 'Amino Acids',
    description: 'L-theanine is an amino acid found in green tea that promotes alpha brain wave activity, reduces anxiety without sedation, and modulates GABA and glutamate pathways relevant to pelvic floor tension. Multiple clinical trials have confirmed its anxiolytic effects, and it is particularly valued for reducing the hypervigilance and anticipatory anxiety that perpetuates hypertonic pelvic floor conditions. It works synergistically with magnesium glycinate for comprehensive nervous system support.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/theanine.webp',
    tags: ['anxiety', 'GABA', 'nervous-system', 'hypertonic-pelvic-floor', 'sleep'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Anxiety reduction and nervous system calm',
  },
  {
    id: 'glycine-collagen',
    name: 'Glycine (Collagen Amino Acid)',
    category: 'Connective Tissue Support',
    subcategory: 'Amino Acids',
    description: 'Glycine is the most abundant amino acid in collagen and is essential for collagen synthesis throughout the body, including the pelvic floor fascia, ligaments, and vaginal tissues. It also functions as an inhibitory neurotransmitter in the spinal cord, reducing pain signal transmission and muscle tension. Supplemental glycine has demonstrated improvements in sleep quality, which is critical for tissue repair and pelvic floor recovery.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/glycine.webp',
    tags: ['collagen', 'connective-tissue', 'sleep', 'pain-reduction', 'pelvic-fascia'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Collagen synthesis and sleep quality',
  },
  {
    id: 'proline-collagen',
    name: 'L-Proline',
    category: 'Connective Tissue Support',
    subcategory: 'Amino Acids',
    description: 'L-proline is an amino acid that is a direct structural component of collagen and is essential for the hydroxylation reactions that give collagen its tensile strength and stability. Adequate proline, along with vitamin C and glycine, is required for the synthesis of strong collagen in pelvic floor fascia, ligaments, and the pubocervical fascia that supports the bladder. It is often included in comprehensive collagen support protocols for pelvic organ prolapse prevention.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/proline.webp',
    tags: ['collagen', 'connective-tissue', 'prolapse-prevention', 'pelvic-fascia', 'ligaments'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Collagen structural support and prolapse prevention',
  },
  {
    id: 'bromelain-enzyme',
    name: 'Bromelain (Proteolytic Enzyme)',
    category: 'Anti-Inflammatory',
    subcategory: 'Proteolytic Enzymes',
    description: 'Bromelain is a proteolytic enzyme from pineapple with potent anti-inflammatory, fibrinolytic, and mucolytic properties used for post-surgical recovery, pelvic adhesions, and chronic inflammatory conditions. Clinical studies have demonstrated its ability to reduce post-surgical swelling, pain, and adhesion formation, making it relevant for women recovering from pelvic surgery or managing endometriosis-related adhesions. It also has anti-platelet effects that support pelvic microcirculation.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/bromelain.webp',
    tags: ['anti-inflammatory', 'post-surgical', 'adhesions', 'endometriosis', 'fibrinolytic'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Post-surgical recovery and adhesion prevention',
  },
  {
    id: 'digestive-bitters-blend',
    name: 'Digestive Bitters Blend',
    category: 'Gut & Mucosal Health',
    subcategory: 'Digestive Tonics',
    description: 'Digestive bitters stimulate bitter taste receptors throughout the digestive tract, triggering the release of digestive enzymes, bile, and stomach acid that support complete digestion and reduce the inflammatory burden from poorly digested food. Adequate digestive function reduces the gut inflammation and intestinal permeability that drive systemic inflammation in pelvic conditions. Traditional bitters formulas include gentian, dandelion, artichoke, and ginger.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/digestive-bitters.webp',
    tags: ['digestion', 'gut-health', 'bile', 'enzymes', 'intestinal-permeability'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Digestive function and gut inflammation',
  },
  {
    id: 'slippery-elm-bark',
    name: 'Slippery Elm Bark',
    category: 'Gut & Mucosal Health',
    subcategory: 'Demulcents',
    description: 'Slippery elm bark is a mucilaginous demulcent herb that coats and soothes inflamed mucosal tissues throughout the digestive and urinary tracts, reducing inflammation and supporting healing. It is used for IBS, inflammatory bowel conditions, and bladder irritability, all of which contribute to pelvic floor dysfunction through referred pain and nervous system sensitization. Its prebiotic fiber content also supports beneficial gut bacteria.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/slippery-elm.webp',
    tags: ['demulcent', 'IBS', 'bladder-irritability', 'gut-health', 'mucosal-healing'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Mucosal soothing and gut-bladder inflammation',
  },
"""

with open('src/data/supplements.ts', 'r') as f:
    content = f.read()

marker = '];\n\nexport default supplements;\n'
if marker not in content:
    print("ERROR: marker not found")
    exit(1)

new_content = content.replace(marker, NEW_ENTRIES + '\n' + marker)

with open('src/data/supplements.ts', 'w') as f:
    f.write(new_content)

import re
count = len(re.findall(r'^\s+id:', new_content, re.MULTILINE))
ids = re.findall(r"id: '([^']+)'", new_content)
from collections import Counter
dupes = {k:v for k,v in Counter(ids).items() if v > 1}
print(f"Total: {count}")
if dupes:
    print(f"Duplicates: {list(dupes.keys())}")
else:
    print("No duplicates - clean!")
