#!/usr/bin/env python3
"""Append 60 more supplement entries to reach 200+ total."""
import re

MARKER = '];\n\nexport default supplements;\n'

NEW = """
  // ─── MORE TCM FORMULAS ────────────────────────────────────────────────────
  {
    id: 'liu-wei-di-huang',
    name: 'Liu Wei Di Huang Wan (Six Flavor Rehmannia)',
    category: 'TCM Formulas',
    subcategory: 'Kidney Yin Tonics',
    description: 'Liu Wei Di Huang Wan is the foundational TCM formula for kidney yin deficiency, which manifests as vaginal dryness, night sweats, urinary frequency, and pelvic floor weakness in menopausal and perimenopausal women. Multiple clinical trials have confirmed its efficacy for menopausal symptoms, with effects comparable to low-dose hormone therapy in some studies. It is the base formula from which many other kidney-tonifying formulas are derived.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/liu-wei.webp',
    tags: ['TCM', 'kidney-yin', 'menopause', 'vaginal-dryness', 'urinary-frequency'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Kidney yin deficiency and menopausal symptoms',
  },
  {
    id: 'gui-pi-tang',
    name: 'Gui Pi Tang (Restore the Spleen)',
    category: 'TCM Formulas',
    subcategory: 'Qi and Blood Tonics',
    description: 'Gui Pi Tang is a classical TCM formula for heart and spleen qi and blood deficiency, used for anxiety, insomnia, fatigue, and heavy menstrual bleeding that depletes qi and blood. In TCM, spleen qi deficiency is a primary cause of pelvic organ prolapse and urinary incontinence through its effects on the holding and lifting function of the middle jiao. It is one of the most commonly used formulas for women with pelvic floor weakness complicated by anxiety and fatigue.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/gui-pi-tang.webp',
    tags: ['TCM', 'spleen-qi', 'prolapse', 'anxiety', 'heavy-bleeding'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Spleen qi deficiency and pelvic organ support',
  },
  {
    id: 'xiao-yao-san',
    name: 'Xiao Yao San (Free and Easy Wanderer)',
    category: 'TCM Formulas',
    subcategory: 'Liver Qi Regulators',
    description: 'Xiao Yao San is the most widely used TCM formula for liver qi stagnation, the pattern most commonly associated with PMS, menstrual irregularity, pelvic pain, and emotional tension that tightens the pelvic floor. Clinical research has demonstrated its efficacy for PMS, dysmenorrhea, and depression, with mechanisms involving serotonin modulation and HPA axis regulation. The modified version Jia Wei Xiao Yao San adds herbs for heat from stagnation, making it appropriate for conditions with inflammation.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/xiao-yao-san.webp',
    tags: ['TCM', 'liver-qi', 'PMS', 'dysmenorrhea', 'emotional-tension'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Liver qi stagnation and PMS',
  },
  {
    id: 'wu-ling-san',
    name: 'Wu Ling San (Five Ingredient Powder)',
    category: 'TCM Formulas',
    subcategory: 'Water Metabolism',
    description: 'Wu Ling San is a classical TCM formula for water metabolism disorders affecting the bladder and urinary system, used for urinary retention, edema, and bladder dysfunction. Modern research has confirmed its diuretic, anti-inflammatory, and bladder-relaxing effects, making it relevant for overactive bladder, interstitial cystitis, and urinary frequency. It is one of the most studied TCM formulas for urological conditions.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/wu-ling-san.webp',
    tags: ['TCM', 'bladder', 'overactive-bladder', 'IC', 'urinary-retention'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bladder dysfunction and water metabolism',
  },
  {
    id: 'ba-zhen-tang',
    name: 'Ba Zhen Tang (Eight Treasure Decoction)',
    category: 'TCM Formulas',
    subcategory: 'Qi and Blood Tonics',
    description: 'Ba Zhen Tang combines the Four Gentlemen (qi tonic) with the Four Substances (blood tonic) to create the most comprehensive TCM formula for qi and blood deficiency, used for postpartum recovery, anemia, and chronic fatigue. For pelvic floor health, it supports tissue repair, muscle strength, and energy production needed for rehabilitation after childbirth, surgery, or chronic illness. It is the foundation of many postpartum recovery protocols in TCM.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/ba-zhen-tang.webp',
    tags: ['TCM', 'postpartum', 'blood-tonic', 'qi-tonic', 'recovery'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Postpartum recovery and qi-blood deficiency',
  },
  // ─── MORE AYURVEDIC ───────────────────────────────────────────────────────
  {
    id: 'guduchi-ayur',
    name: 'Guduchi (Tinospora cordifolia)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Immune Tonics',
    description: 'Guduchi is an Ayurvedic herb known as "the divine nectar" for its immune-modulating, anti-inflammatory, and adaptogenic properties. Research has demonstrated its ability to reduce inflammatory cytokines relevant to conditions like interstitial cystitis, endometriosis, and chronic pelvic pain syndrome. It is used in Ayurveda for conditions involving ama (toxic accumulation) and chronic inflammation in the lower abdomen and reproductive organs.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/guduchi.webp',
    tags: ['Ayurveda', 'anti-inflammatory', 'interstitial-cystitis', 'endometriosis', 'immune'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Chronic pelvic inflammation and immune modulation',
  },
  {
    id: 'lodhra',
    name: 'Lodhra (Symplocos racemosa)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Uterine Astringents',
    description: 'Lodhra is a classical Ayurvedic uterine astringent used for excessive menstrual bleeding, vaginal discharge, and pelvic organ prolapse. Its tannins and alkaloids have demonstrated uterine-toning, anti-inflammatory, and estrogenic effects in research. In Ayurveda it is considered a specific remedy for conditions involving laxity and downward displacement of pelvic organs.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/lodhra.webp',
    tags: ['Ayurveda', 'uterine-tonic', 'prolapse', 'menorrhagia', 'vaginal-discharge'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine tone and pelvic organ support',
  },
  {
    id: 'vidari-kanda',
    name: 'Vidari Kanda (Pueraria tuberosa)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Rasayanas',
    description: 'Vidari kanda is an Ayurvedic rasayana (rejuvenative) herb for female reproductive tissue, containing isoflavones and phytoestrogens that support vaginal tissue health and hormonal balance. It is used for vaginal atrophy, decreased libido, and postmenopausal pelvic changes where tissue thinning contributes to pain and dysfunction. Its anabolic and tissue-building properties make it relevant for postpartum recovery and rebuilding pelvic floor strength.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/vidari-kanda.webp',
    tags: ['Ayurveda', 'phytoestrogens', 'vaginal-atrophy', 'menopause', 'postpartum'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Vaginal tissue health and phytoestrogenic support',
  },
  {
    id: 'kapikacchu',
    name: 'Kapikacchu / Mucuna (Mucuna pruriens)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Nervines',
    description: 'Mucuna pruriens is an Ayurvedic herb containing L-DOPA, the direct precursor to dopamine, making it relevant for conditions involving dopamine dysregulation including restless legs syndrome, pelvic floor tension, and sexual dysfunction. Dopamine plays a key role in pelvic floor relaxation and sexual arousal, and deficiency contributes to anorgasmia and hypertonic pelvic floor conditions. It also contains serotonin precursors and has demonstrated testosterone-supporting effects in men.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/mucuna.webp',
    tags: ['Ayurveda', 'dopamine', 'sexual-function', 'hypertonic-pelvic-floor', 'nervine'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Dopamine support and sexual function',
  },
  {
    id: 'amalaki',
    name: 'Amalaki (Emblica officinalis / Amla)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Vitamin C Sources',
    description: 'Amalaki is one of the richest natural sources of vitamin C and is considered the most important rasayana (rejuvenative) herb in Ayurveda for its antioxidant, anti-inflammatory, and tissue-building properties. Its vitamin C content supports collagen synthesis in pelvic floor fascia and ligaments, while its tannins have astringent effects on mucosal tissues. It is used in Ayurveda for conditions involving tissue degeneration, inflammation, and weakness throughout the reproductive system.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/amalaki.webp',
    tags: ['Ayurveda', 'vitamin-C', 'collagen', 'antioxidant', 'tissue-repair'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Collagen synthesis and tissue rejuvenation',
  },
  // ─── MORE WESTERN HERBS ───────────────────────────────────────────────────
  {
    id: 'goldenrod',
    name: 'Goldenrod (Solidago virgaurea)',
    category: 'Western Herbs',
    subcategory: 'Urinary Tonics',
    description: 'Goldenrod is a European urinary tonic with anti-inflammatory, antispasmodic, and mild diuretic properties used for bladder inflammation, kidney stones, and urinary tract infections. Clinical studies have confirmed its efficacy for reducing bladder inflammation and supporting urinary tract health. It is particularly useful for the type of bladder irritability that accompanies interstitial cystitis and pelvic floor hypertonicity.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/goldenrod.webp',
    tags: ['urinary-tonic', 'bladder-inflammation', 'interstitial-cystitis', 'kidney-stones', 'Western-herbs'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bladder inflammation and urinary tract health',
  },
  {
    id: 'wild-yam',
    name: 'Wild Yam (Dioscorea villosa)',
    category: 'Western Herbs',
    subcategory: 'Hormonal Support',
    description: 'Wild yam contains diosgenin, a steroidal saponin that is a laboratory precursor to progesterone, though the human body cannot convert it directly. Topical wild yam creams are widely used for menopausal symptoms and are thought to work through skin absorption of diosgenin and its metabolites. For pelvic health, it is used for progesterone deficiency patterns, including PMS, luteal phase deficiency, and perimenopausal pelvic floor changes.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/wild-yam.webp',
    tags: ['progesterone', 'menopause', 'PMS', 'hormonal-balance', 'Western-herbs'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Progesterone support and hormonal balance',
  },
  {
    id: 'ladies-mantle',
    name: "Lady's Mantle (Alchemilla vulgaris)",
    category: 'Western Herbs',
    subcategory: 'Uterine Astringents',
    description: "Lady's mantle is a traditional European herb for women's reproductive health, used as a uterine astringent for heavy periods, vaginal discharge, and pelvic organ prolapse. Its tannins tone and tighten pelvic tissues, while its progesterogenic effects support the luteal phase and reduce estrogen dominance patterns. It is often combined with shepherd's purse for heavy bleeding and with cramp bark for dysmenorrhea.",
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/ladys-mantle.webp',
    tags: ['uterine-tonic', 'prolapse', 'heavy-periods', 'progesterone', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine astringency and pelvic tissue tone',
  },
  {
    id: 'blue-cohosh',
    name: 'Blue Cohosh (Caulophyllum thalictroides)',
    category: 'Western Herbs',
    subcategory: 'Uterine Stimulants',
    description: 'Blue cohosh is a traditional Native American and eclectic medicine herb used as a uterine tonic and stimulant for conditions involving pelvic stagnation, delayed labor, and postpartum recovery. Its caulosaponin and methylcytisine have demonstrated uterine-stimulating effects, making it appropriate only for specific clinical situations under qualified guidance. It is used in combination formulas for pelvic congestion, chronic pelvic pain with stagnation patterns, and postpartum uterine atony.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/blue-cohosh.webp',
    tags: ['uterine-stimulant', 'pelvic-stagnation', 'postpartum', 'Western-herbs', 'traditional'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine stimulation and pelvic stagnation',
  },
  // ─── MINERALS & VITAMINS ──────────────────────────────────────────────────
  {
    id: 'iron-bisglycinate',
    name: 'Iron Bisglycinate',
    category: 'Blood & Energy Support',
    subcategory: 'Minerals',
    description: 'Iron deficiency is the most common nutritional deficiency in women of reproductive age, contributing to fatigue, poor exercise tolerance, and impaired pelvic floor muscle recovery. Iron bisglycinate is the most gentle and well-absorbed form, causing significantly less constipation and gut irritation than ferrous sulfate. Adequate iron is essential for collagen synthesis, muscle oxygenation, and the energy production needed for pelvic floor rehabilitation.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/iron.webp',
    tags: ['iron-deficiency', 'anemia', 'fatigue', 'muscle-recovery', 'collagen'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Iron deficiency and muscle recovery',
  },
  {
    id: 'vitamin-k2',
    name: 'Vitamin K2 (MK-7)',
    category: 'Bone & Connective Tissue',
    subcategory: 'Fat-Soluble Vitamins',
    description: 'Vitamin K2 activates matrix Gla protein (MGP), which prevents calcium deposition in soft tissues and directs it to bones and teeth. For pelvic floor health, K2 is relevant to pelvic ligament and fascia integrity, as calcification of pelvic ligaments contributes to rigidity and pain. It works synergistically with vitamin D3 and magnesium for comprehensive pelvic connective tissue support.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/vitamin-k2.webp',
    tags: ['bone-health', 'connective-tissue', 'calcium-metabolism', 'pelvic-ligaments', 'vitamin-D'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue integrity and calcium metabolism',
  },
  {
    id: 'vitamin-a',
    name: 'Vitamin A (Retinol)',
    category: 'Mucosal Health',
    subcategory: 'Fat-Soluble Vitamins',
    description: 'Vitamin A (retinol) is essential for the maintenance of mucosal epithelial tissues throughout the body, including the vaginal epithelium, bladder lining, and intestinal mucosa. Deficiency contributes to vaginal atrophy, increased susceptibility to infections, and impaired mucosal healing. It works synergistically with zinc and vitamin C for comprehensive mucosal tissue support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/vitamin-a.webp',
    tags: ['mucosal-health', 'vaginal-epithelium', 'bladder-lining', 'immune', 'tissue-repair'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Mucosal tissue health and vaginal epithelium',
  },
  {
    id: 'zinc',
    name: 'Zinc (Bisglycinate or Picolinate)',
    category: 'Immune & Reproductive Health',
    subcategory: 'Minerals',
    description: 'Zinc is essential for immune function, wound healing, collagen synthesis, and reproductive hormone production, all of which are relevant to pelvic floor health. It is required for the activity of over 300 enzymes including those involved in tissue repair, estrogen metabolism, and progesterone synthesis. Zinc deficiency is common in women with heavy periods, vegetarians, and those on oral contraceptives, and contributes to impaired healing and hormonal imbalance.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/zinc.webp',
    tags: ['immune', 'wound-healing', 'collagen', 'hormonal-balance', 'reproductive-health'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Immune function and reproductive hormone support',
  },
  {
    id: 'copper',
    name: 'Copper (Bisglycinate)',
    category: 'Connective Tissue Support',
    subcategory: 'Minerals',
    description: 'Copper is a cofactor for lysyl oxidase, the enzyme that cross-links collagen and elastin fibers in connective tissue, making it essential for the tensile strength of pelvic floor fascia and ligaments. Copper deficiency, which can be induced by excess zinc supplementation, contributes to connective tissue weakness and laxity. It is best supplemented in a balanced ratio with zinc (approximately 1mg copper per 10-15mg zinc).',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/copper.webp',
    tags: ['connective-tissue', 'collagen', 'elastin', 'pelvic-ligaments', 'zinc-balance'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue cross-linking and pelvic ligament strength',
  },
  {
    id: 'boron',
    name: 'Boron',
    category: 'Hormonal Balance',
    subcategory: 'Trace Minerals',
    description: 'Boron is a trace mineral that supports estrogen and testosterone metabolism, bone density, and cognitive function. Research has shown that boron supplementation increases serum estradiol and testosterone levels, reduces inflammatory cytokines, and improves magnesium absorption. For pelvic floor health, its hormonal support is relevant to maintaining tissue integrity in perimenopause and menopause.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/boron.webp',
    tags: ['hormonal-balance', 'estrogen', 'testosterone', 'bone-density', 'menopause'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Hormonal support and bone density',
  },
  {
    id: 'silica',
    name: 'Silica (Orthosilicic Acid)',
    category: 'Connective Tissue Support',
    subcategory: 'Minerals',
    description: 'Silica is essential for collagen synthesis and the structural integrity of connective tissues, skin, hair, and nails. Orthosilicic acid (OSA) is the most bioavailable form and has demonstrated the ability to increase collagen synthesis and improve skin elasticity in clinical studies. For pelvic floor health, adequate silica supports the tensile strength of pelvic fascia and ligaments that hold pelvic organs in place.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/silica.webp',
    tags: ['connective-tissue', 'collagen', 'pelvic-fascia', 'ligaments', 'tissue-strength'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Connective tissue strength and collagen synthesis',
  },
  // ─── SPECIALIZED SUPPLEMENTS ──────────────────────────────────────────────
  {
    id: 'prebiotic-fiber',
    name: 'Prebiotic Fiber (PHGG)',
    category: 'Microbiome Support',
    subcategory: 'Gut Prebiotics',
    description: 'Partially hydrolyzed guar gum (PHGG) is a prebiotic fiber that feeds beneficial gut bacteria producing short-chain fatty acids, regulating estrogen metabolism, and reducing systemic inflammation relevant to pelvic floor health. It is particularly well-tolerated and has demonstrated efficacy for IBS-related constipation and diarrhea, both of which directly impact pelvic floor function. A healthy gut microbiome reduces the beta-glucuronidase activity that drives estrogen recirculation.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/prebiotic-fiber.webp',
    tags: ['gut-health', 'constipation', 'IBS', 'estrogen-metabolism', 'microbiome'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut microbiome and bowel regularity',
  },
  {
    id: 'l-glutamine',
    name: 'L-Glutamine',
    category: 'Gut & Mucosal Health',
    subcategory: 'Amino Acids',
    description: 'L-glutamine is the primary fuel source for intestinal epithelial cells and is essential for maintaining gut barrier integrity, which is compromised in many women with chronic pelvic pain, endometriosis, and IBS. Clinical studies have demonstrated its ability to reduce intestinal permeability, decrease gut inflammation, and support mucosal healing. For pelvic floor health, a healthy gut barrier reduces the systemic inflammatory load that drives pelvic tissue inflammation and sensitization.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/l-glutamine.webp',
    tags: ['gut-health', 'leaky-gut', 'IBS', 'intestinal-permeability', 'anti-inflammatory'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Gut barrier integrity and mucosal healing',
  },
  {
    id: 'zinc-carnosine',
    name: 'Zinc Carnosine',
    category: 'Gut & Mucosal Health',
    subcategory: 'Mucosal Protectants',
    description: 'Zinc carnosine is a chelated form of zinc and L-carnosine with demonstrated mucosal protective effects in the gut and urinary tract, relevant to leaky gut, intestinal permeability, and bladder lining integrity. Intestinal permeability is increasingly recognized as a driver of systemic inflammation in conditions like endometriosis, IC, and chronic pelvic pain. It supports tight junction integrity, reduces gut inflammation, and has been used clinically for gastric ulcers and intestinal permeability.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/zinc-carnosine.webp',
    tags: ['gut-health', 'leaky-gut', 'bladder-lining', 'endometriosis', 'IC'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Mucosal integrity and intestinal permeability',
  },
  {
    id: 'cats-claw',
    name: "Cat's Claw (Uncaria tomentosa)",
    category: 'Anti-Inflammatory',
    subcategory: 'Bark Extracts',
    description: "Cat's claw is a South American herb with potent anti-inflammatory, immunomodulatory, and DNA-repair properties, used for autoimmune conditions, chronic inflammatory pain, and conditions involving NF-kB-driven inflammation. Its oxindole alkaloids modulate immune function and reduce inflammatory cytokines relevant to endometriosis, IC, and chronic pelvic pain syndrome. It is used in integrative oncology and for conditions involving chronic immune activation.",
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/cats-claw.webp',
    tags: ['anti-inflammatory', 'autoimmune', 'endometriosis', 'IC', 'NF-kB'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Autoimmune inflammation and chronic pelvic pain',
  },
  {
    id: 'castor-oil-topical',
    name: 'Castor Oil (Topical / Packs)',
    category: 'Topical & External',
    subcategory: 'Lymphatic Support',
    description: 'Castor oil packs applied to the lower abdomen are a traditional naturopathic therapy for improving pelvic circulation, reducing inflammation, and supporting lymphatic drainage in the pelvis. Ricinoleic acid, castor oil\'s primary fatty acid, has demonstrated anti-inflammatory, analgesic, and lymphagogue effects in research. They are used for endometriosis, fibroids, pelvic adhesions, and constipation, and many women report significant pain reduction with consistent use.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/castor-oil.webp',
    tags: ['topical', 'endometriosis', 'fibroids', 'lymphatic', 'pelvic-circulation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Pelvic circulation and lymphatic drainage',
  },
  {
    id: 'hemp-cbd',
    name: 'CBD (Cannabidiol)',
    category: 'Pain & Nervous System',
    subcategory: 'Cannabinoids',
    description: 'CBD interacts with the endocannabinoid system, which plays a significant role in pelvic pain modulation, bladder function, and nervous system regulation relevant to pelvic floor dysfunction. Emerging research suggests CBD may reduce central sensitization, bladder hyperactivity, and pelvic muscle tension through its effects on CB1 and CB2 receptors and TRPV1 channels. It is being studied for endometriosis, IC, and vulvodynia with promising preliminary results.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/cbd.webp',
    tags: ['pain', 'endocannabinoid', 'bladder', 'central-sensitization', 'vulvodynia'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Pelvic pain and nervous system regulation',
  },
  {
    id: 'pine-pollen',
    name: 'Pine Pollen',
    category: 'Hormonal Balance',
    subcategory: 'Phytoandrogens',
    description: 'Pine pollen contains phytoandrogens including testosterone, DHEA, and androstenedione in small amounts, along with brassinosteroids that may support androgen levels in women with low testosterone contributing to low libido, fatigue, and reduced pelvic floor muscle tone. It is used in Chinese medicine and Western herbalism for conditions involving androgen deficiency, including postmenopausal sexual dysfunction and adrenal fatigue. The tincture form provides better absorption of the androgenic compounds than powder.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/pine-pollen.webp',
    tags: ['androgens', 'libido', 'testosterone', 'menopause', 'adrenal'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Androgen support and libido',
  },
  {
    id: 'cordyceps',
    name: 'Cordyceps Mushroom',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Cordyceps is an adaptogenic mushroom that supports adrenal function, mitochondrial energy production, and oxygen utilization — all relevant to pelvic floor rehabilitation and recovery from chronic fatigue associated with pelvic conditions. It increases ATP production in muscle cells and has demonstrated improvements in exercise capacity and recovery in clinical trials. For women with pelvic floor dysfunction complicated by chronic fatigue or adrenal exhaustion, it supports the energy needed for rehabilitation.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/cordyceps.webp',
    tags: ['adaptogen', 'adrenal', 'energy', 'exercise-recovery', 'mitochondria'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Energy production and adrenal support',
  },
  {
    id: 'dhea-topical',
    name: 'Topical DHEA (Prasterone)',
    category: 'Hormonal Topicals',
    subcategory: 'Vaginal Androgens',
    description: 'Topical DHEA (prasterone) is FDA-approved for dyspareunia due to menopause and works by converting locally to both estrogen and testosterone in vaginal tissues, restoring tissue health without significant systemic hormone exposure. It addresses the androgen component of vaginal atrophy that estrogen alone does not fully treat, including clitoral sensitivity, libido, and vaginal tissue thickness. It is an option for women who cannot or prefer not to use estrogen.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/dhea-topical.webp',
    tags: ['menopause', 'dyspareunia', 'libido', 'vaginal-atrophy', 'DHEA'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Dyspareunia and vaginal androgen deficiency',
  },
  {
    id: 'wobenzym',
    name: 'Wobenzym (Systemic Enzyme Blend)',
    category: 'Systemic Enzymes',
    subcategory: 'Enzyme Blends',
    description: 'Wobenzym is a German systemic enzyme formula combining pancreatin, bromelain, papain, trypsin, chymotrypsin, and rutin with extensive clinical research for inflammatory conditions, post-surgical recovery, and autoimmune diseases. Its anti-inflammatory effects are comparable to NSAIDs in some studies without the gastrointestinal side effects, making it relevant for chronic pelvic pain management. It is widely used in European integrative medicine for endometriosis, pelvic inflammatory disease, and post-surgical adhesion prevention.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/wobenzym.webp',
    tags: ['systemic-enzymes', 'endometriosis', 'post-surgical', 'anti-inflammatory', 'autoimmune'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Systemic inflammation and post-surgical recovery',
  },
  {
    id: 'sulforaphane',
    name: 'Sulforaphane (Broccoli Sprout Extract)',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Metabolism',
    description: 'Sulforaphane activates the Nrf2 pathway, the master regulator of antioxidant and detoxification genes, and supports phase 2 liver detoxification of estrogens and other hormones. It has demonstrated anti-cancer, anti-inflammatory, and estrogen-modulating effects in research, making it relevant for estrogen-driven conditions like endometriosis, fibroids, and hormonal pelvic pain. It works synergistically with DIM and calcium D-glucarate for comprehensive estrogen metabolism support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/sulforaphane.webp',
    tags: ['estrogen-metabolism', 'Nrf2', 'endometriosis', 'fibroids', 'detox'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen detoxification and Nrf2 activation',
  },
  {
    id: 'alpha-lipoic-acid',
    name: 'Alpha Lipoic Acid (ALA)',
    category: 'Anti-Inflammatory',
    subcategory: 'Antioxidants',
    description: 'Alpha lipoic acid is a universal antioxidant that works in both fat-soluble and water-soluble environments, regenerates other antioxidants including vitamins C and E and glutathione, and has demonstrated neuroprotective effects relevant to pudendal neuralgia and pelvic nerve pain. Clinical studies have shown its efficacy for diabetic neuropathy, and it is used in integrative medicine for neuropathic pelvic pain conditions. It also has anti-inflammatory effects on NF-kB pathways relevant to chronic pelvic inflammation.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/ala.webp',
    tags: ['neuropathy', 'pudendal-neuralgia', 'antioxidant', 'nerve-pain', 'anti-inflammatory'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Neuropathic pain and antioxidant support',
  },
  {
    id: 'coq10',
    name: 'CoQ10 (Ubiquinol)',
    category: 'Energy & Mitochondrial Support',
    subcategory: 'Mitochondrial Nutrients',
    description: 'CoQ10 (as ubiquinol, the active form) is essential for mitochondrial energy production in all cells including pelvic floor muscles, and has demonstrated anti-inflammatory, antioxidant, and fertility-supporting effects. It is particularly relevant for women with endometriosis, where mitochondrial dysfunction and oxidative stress in pelvic tissues contribute to pain and infertility. Ubiquinol is 3-8x more bioavailable than ubiquinone and is the preferred form for women over 40.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/coq10.webp',
    tags: ['mitochondria', 'energy', 'endometriosis', 'fertility', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Mitochondrial energy and endometriosis support',
  },
  {
    id: 'phosphatidylserine',
    name: 'Phosphatidylserine',
    category: 'Nervous System Support',
    subcategory: 'Phospholipids',
    description: 'Phosphatidylserine is a phospholipid essential for neuronal membrane integrity and has demonstrated the ability to reduce cortisol response to exercise and psychological stress, making it relevant for women with stress-driven pelvic floor dysfunction. Elevated cortisol maintains sympathetic nervous system dominance that prevents pelvic floor relaxation and healing. It is used in integrative medicine for HPA axis dysregulation, adrenal fatigue, and stress-related conditions.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/phosphatidylserine.webp',
    tags: ['cortisol', 'HPA-axis', 'stress', 'nervous-system', 'adrenal'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Cortisol regulation and HPA axis support',
  },
  {
    id: 'gaba-supplement',
    name: 'GABA (Gamma-Aminobutyric Acid)',
    category: 'Nervous System Support',
    subcategory: 'Neurotransmitters',
    description: 'GABA is the primary inhibitory neurotransmitter that reduces neuronal excitability and promotes relaxation throughout the nervous system, including the pudendal nerve pathways that innervate the pelvic floor. Supplemental GABA, particularly in the PharmaGABA form, has demonstrated anxiolytic and muscle-relaxing effects in clinical studies. For women with hypertonic pelvic floor conditions driven by nervous system hyperactivation, GABA support may reduce the baseline tension that prevents healing.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/gaba.webp',
    tags: ['GABA', 'anxiety', 'hypertonic-pelvic-floor', 'nervous-system', 'muscle-relaxant'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Nervous system inhibition and pelvic floor relaxation',
  },
  {
    id: 'theanine',
    name: 'L-Theanine',
    category: 'Nervous System Support',
    subcategory: 'Amino Acids',
    description: 'L-theanine is an amino acid found in green tea that promotes alpha brain wave activity, reduces anxiety without sedation, and modulates GABA and glutamate pathways relevant to pelvic floor tension. Multiple clinical trials have confirmed its anxiolytic effects, and it is particularly valued for reducing the hypervigilance and anticipatory anxiety that perpetuates hypertonic pelvic floor conditions. It works synergistically with magnesium glycinate for comprehensive nervous system support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/theanine.webp',
    tags: ['anxiety', 'GABA', 'nervous-system', 'hypertonic-pelvic-floor', 'sleep'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Anxiety reduction and nervous system calm',
  },
  {
    id: 'glycine',
    name: 'Glycine',
    category: 'Connective Tissue Support',
    subcategory: 'Amino Acids',
    description: 'Glycine is the most abundant amino acid in collagen and is essential for collagen synthesis throughout the body, including the pelvic floor fascia, ligaments, and vaginal tissues. It also functions as an inhibitory neurotransmitter in the spinal cord, reducing pain signal transmission and muscle tension. Supplemental glycine has demonstrated improvements in sleep quality, which is critical for tissue repair and pelvic floor recovery.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/glycine.webp',
    tags: ['collagen', 'connective-tissue', 'sleep', 'pain-reduction', 'pelvic-fascia'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Collagen synthesis and sleep quality',
  },
  {
    id: 'proline',
    name: 'L-Proline',
    category: 'Connective Tissue Support',
    subcategory: 'Amino Acids',
    description: 'L-proline is an amino acid that is a direct structural component of collagen and is essential for the hydroxylation reactions that give collagen its tensile strength and stability. Adequate proline, along with vitamin C and glycine, is required for the synthesis of strong collagen in pelvic floor fascia, ligaments, and the pubocervical fascia that supports the bladder. It is often included in comprehensive collagen support protocols for pelvic organ prolapse prevention.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/proline.webp',
    tags: ['collagen', 'connective-tissue', 'prolapse-prevention', 'pelvic-fascia', 'ligaments'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Collagen structural support and prolapse prevention',
  },
  {
    id: 'bromelain',
    name: 'Bromelain',
    category: 'Anti-Inflammatory',
    subcategory: 'Proteolytic Enzymes',
    description: 'Bromelain is a proteolytic enzyme from pineapple with potent anti-inflammatory, fibrinolytic, and mucolytic properties used for post-surgical recovery, pelvic adhesions, and chronic inflammatory conditions. Clinical studies have demonstrated its ability to reduce post-surgical swelling, pain, and adhesion formation, making it relevant for women recovering from pelvic surgery or managing endometriosis-related adhesions. It also has anti-platelet effects that support pelvic microcirculation.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/bromelain.webp',
    tags: ['anti-inflammatory', 'post-surgical', 'adhesions', 'endometriosis', 'fibrinolytic'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Post-surgical recovery and adhesion prevention',
  },
  {
    id: 'papaya-enzyme',
    name: 'Papain (Papaya Enzyme)',
    category: 'Digestive & Systemic Enzymes',
    subcategory: 'Proteolytic Enzymes',
    description: 'Papain is a proteolytic enzyme from papaya with anti-inflammatory, digestive, and wound-healing properties used for digestive support and systemic inflammation. It supports protein digestion, reducing the inflammatory burden from incompletely digested proteins that can trigger immune reactions relevant to pelvic floor conditions. When taken on an empty stomach, it acts systemically to reduce inflammation and support tissue repair.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/papain.webp',
    tags: ['digestive-enzyme', 'anti-inflammatory', 'wound-healing', 'protein-digestion', 'systemic'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Digestive support and systemic anti-inflammatory',
  },
  {
    id: 'digestive-bitters',
    name: 'Digestive Bitters',
    category: 'Gut & Mucosal Health',
    subcategory: 'Digestive Tonics',
    description: 'Digestive bitters stimulate bitter taste receptors throughout the digestive tract, triggering the release of digestive enzymes, bile, and stomach acid that support complete digestion and reduce the inflammatory burden from poorly digested food. Adequate digestive function reduces the gut inflammation and intestinal permeability that drive systemic inflammation in pelvic conditions. Traditional bitters formulas include gentian, dandelion, artichoke, and ginger.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/digestive-bitters.webp',
    tags: ['digestion', 'gut-health', 'bile', 'enzymes', 'intestinal-permeability'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Digestive function and gut inflammation',
  },
  {
    id: 'slippery-elm',
    name: 'Slippery Elm Bark',
    category: 'Gut & Mucosal Health',
    subcategory: 'Demulcents',
    description: 'Slippery elm bark is a mucilaginous demulcent herb that coats and soothes inflamed mucosal tissues throughout the digestive and urinary tracts, reducing inflammation and supporting healing. It is used for IBS, inflammatory bowel conditions, and bladder irritability, all of which contribute to pelvic floor dysfunction through referred pain and nervous system sensitization. Its prebiotic fiber content also supports beneficial gut bacteria.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/slippery-elm.webp',
    tags: ['demulcent', 'IBS', 'bladder-irritability', 'gut-health', 'mucosal-healing'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Mucosal soothing and gut-bladder inflammation',
  },
  {
    id: 'marshmallow-root',
    name: 'Marshmallow Root (Althaea officinalis)',
    category: 'Gut & Mucosal Health',
    subcategory: 'Demulcents',
    description: 'Marshmallow root is a potent urinary and digestive demulcent with mucilaginous polysaccharides that coat and protect inflamed mucosal surfaces in the bladder, urethra, and intestines. It is used for interstitial cystitis, urethral irritation, and bladder pain syndrome, providing symptomatic relief while supporting mucosal healing. Cold-water extraction preserves the mucilage content better than hot infusion.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/marshmallow-root.webp',
    tags: ['urinary-demulcent', 'interstitial-cystitis', 'bladder-pain', 'mucosal-healing', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Bladder and urethral mucosal protection',
  },
"""

with open('src/data/supplements.ts', 'r') as f:
    content = f.read()

marker = '];\n\nexport default supplements;\n'
if marker not in content:
    print("ERROR: marker not found")
    exit(1)

new_content = content.replace(marker, NEW + '\n' + marker)

with open('src/data/supplements.ts', 'w') as f:
    f.write(new_content)

import re
count = len(re.findall(r"^\s+id:", new_content, re.MULTILINE))
print(f"SUCCESS: {count} total supplement entries")
