#!/usr/bin/env python3
"""Append 50 more supplement entries to reach 200+ total."""
import re

MARKER = '];\n\nexport default supplements;\n'

NEW = """
  // ─── TCM HERBS ────────────────────────────────────────────────────────────
  {
    id: 'dong-quai',
    name: 'Dong Quai (Angelica sinensis)',
    category: 'TCM Herbs',
    subcategory: 'Blood Tonics',
    description: 'Dong quai is the most widely used herb in Traditional Chinese Medicine for women\'s reproductive health, often called the "female ginseng" for its ability to nourish and move blood. It contains ferulic acid and ligustilide, which relax uterine muscle, reduce menstrual cramping, and support circulation to the pelvic organs. In TCM, it is used for blood deficiency patterns that manifest as pelvic pain, scanty periods, and postpartum recovery.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/dong-quai.webp',
    tags: ['TCM', 'menstrual-pain', 'blood-tonic', 'postpartum', 'pelvic-circulation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Menstrual regulation and pelvic circulation',
  },
  {
    id: 'bai-shao',
    name: 'White Peony Root (Bai Shao)',
    category: 'TCM Herbs',
    subcategory: 'Blood Tonics',
    description: 'White peony root is a foundational TCM herb for nourishing liver blood and softening the liver, which in Chinese medicine governs the smooth flow of qi through the pelvis and reproductive organs. Paeoniflorin, its primary compound, has demonstrated anti-spasmodic, anti-inflammatory, and hormone-modulating effects in clinical research. It is commonly combined with licorice root (Shao Yao Gan Cao Tang) for pelvic cramping, vaginismus, and hypertonic pelvic floor conditions.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/bai-shao.webp',
    tags: ['TCM', 'liver-blood', 'anti-spasmodic', 'vaginismus', 'hypertonic-pelvic-floor'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Pelvic muscle spasm and liver blood nourishment',
  },
  {
    id: 'chuan-xiong',
    name: 'Chuan Xiong (Ligusticum chuanxiong)',
    category: 'TCM Herbs',
    subcategory: 'Blood Movers',
    description: 'Chuan xiong is one of the primary blood-moving herbs in TCM, used to invigorate blood circulation and relieve pain in the lower abdomen and pelvis. Its active compounds tetramethylpyrazine and ferulic acid have vasodilatory, anti-platelet, and analgesic properties that support pelvic blood flow and reduce stagnation-type pain. It is frequently combined with dong quai in formulas for endometriosis, dysmenorrhea, and pelvic congestion syndrome.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/chuan-xiong.webp',
    tags: ['TCM', 'blood-moving', 'endometriosis', 'pelvic-pain', 'dysmenorrhea'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Blood stagnation and pelvic pain',
  },
  {
    id: 'yi-mu-cao',
    name: 'Motherwort (Yi Mu Cao)',
    category: 'TCM Herbs',
    subcategory: 'Uterine Tonics',
    description: 'Motherwort is used in both TCM and Western herbalism as a uterine tonic that moves blood, reduces cramping, and supports postpartum uterine involution. Leonurine, its primary alkaloid, stimulates uterine contractions and has demonstrated anti-platelet and cardioprotective effects in research. It is traditionally used for delayed periods, postpartum recovery, and pelvic stagnation patterns with a sensation of heaviness or fullness.',
    asin: 'B00FIOD9UE',
    imageKey: 'supplements/motherwort.webp',
    tags: ['TCM', 'uterine-tonic', 'postpartum', 'menstrual-regulation', 'pelvic-stagnation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine health and postpartum recovery',
  },
  {
    id: 'tu-si-zi',
    name: 'Cuscuta Seed (Tu Si Zi)',
    category: 'TCM Herbs',
    subcategory: 'Kidney Yang Tonics',
    description: 'Cuscuta seed tonifies kidney yang and essence in TCM, making it relevant for urinary incontinence, frequent urination, and pelvic floor weakness associated with kidney deficiency patterns. Research has shown it contains flavonoids that support estrogen-like activity, bone density, and reproductive organ health. It is commonly used in formulas for stress urinary incontinence, nocturia, and postmenopausal pelvic floor changes.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/tu-si-zi.webp',
    tags: ['TCM', 'kidney-yang', 'incontinence', 'urinary-frequency', 'menopause'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Kidney yang and urinary incontinence',
  },
  {
    id: 'huang-qi',
    name: 'Astragalus Root (Huang Qi)',
    category: 'TCM Herbs',
    subcategory: 'Qi Tonics',
    description: 'Astragalus is a premier qi tonic in TCM that strengthens the spleen and lung qi, which in Chinese medicine supports the lifting and holding function relevant to pelvic organ prolapse and urinary incontinence. Its polysaccharides and saponins have demonstrated immune-modulating, anti-inflammatory, and adaptogenic effects in extensive research. It is used in formulas for prolapse, chronic fatigue, and pelvic floor weakness from a qi deficiency pattern.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/astragalus.webp',
    tags: ['TCM', 'qi-tonic', 'prolapse', 'immune-support', 'adaptogen'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Qi deficiency and pelvic organ support',
  },
  {
    id: 'ze-xie',
    name: 'Alisma (Ze Xie)',
    category: 'TCM Herbs',
    subcategory: 'Dampness-Clearing',
    description: 'Alisma is a TCM herb that drains dampness and clears heat from the lower jiao, the energetic zone corresponding to the bladder, kidneys, and reproductive organs. It has diuretic, anti-inflammatory, and lipid-lowering properties, and is used for urinary tract infections, interstitial cystitis, and bladder irritability with heat signs. In formulas like Liu Wei Di Huang Wan, it balances the tonifying herbs to prevent stagnation.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/ze-xie.webp',
    tags: ['TCM', 'dampness', 'UTI', 'interstitial-cystitis', 'bladder-heat'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Bladder heat and urinary tract inflammation',
  },
  {
    id: 'fu-ling',
    name: 'Poria Mushroom (Fu Ling)',
    category: 'TCM Herbs',
    subcategory: 'Dampness-Resolving',
    description: 'Poria is one of the most commonly used herbs in TCM, appearing in hundreds of classical formulas for its ability to calm the mind, strengthen the spleen, and resolve dampness. Its beta-glucans have demonstrated significant immune-modulating and anti-inflammatory effects in modern research. For pelvic health, it is used in formulas addressing vaginal discharge, urinary frequency, and anxiety-related pelvic floor tension.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/poria.webp',
    tags: ['TCM', 'dampness', 'vaginal-discharge', 'anxiety', 'immune-support'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Dampness resolution and nervous system calm',
  },
  {
    id: 'gui-zhi',
    name: 'Cinnamon Twig (Gui Zhi)',
    category: 'TCM Herbs',
    subcategory: 'Yang-Warming',
    description: 'Cinnamon twig warms and unblocks the channels in TCM, making it central to formulas for cold-type pelvic pain, endometriosis with cold patterns, and poor circulation to the pelvic organs. Cinnamaldehyde has demonstrated anti-inflammatory, vasodilatory, and insulin-sensitizing effects relevant to conditions like PCOS that affect pelvic floor function. The classical formula Gui Zhi Fu Ling Wan uses it specifically for uterine blood stagnation and pelvic masses.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/gui-zhi.webp',
    tags: ['TCM', 'cold-pelvic-pain', 'endometriosis', 'PCOS', 'blood-stagnation'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Cold-type pelvic pain and blood stagnation',
  },
  // ─── AYURVEDIC HERBS ──────────────────────────────────────────────────────
  {
    id: 'shatavari',
    name: 'Shatavari (Asparagus racemosus)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Rasayanas',
    description: 'Shatavari is the primary Ayurvedic herb for women\'s reproductive health, its name meaning "she who possesses a hundred husbands" in reference to its profound support for female vitality and fertility. Its steroidal saponins (shatavarin I-IV) have demonstrated estrogen-modulating, anti-inflammatory, and adaptogenic effects, making it relevant for vaginal dryness, perimenopause, and pelvic tissue health. It is used throughout a woman\'s life cycle for menstrual regulation, postpartum recovery, and menopausal transition.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/shatavari.webp',
    tags: ['Ayurveda', 'estrogen', 'vaginal-dryness', 'menopause', 'postpartum'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Female reproductive vitality and hormonal balance',
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha (Withania somnifera)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Adaptogens',
    description: 'Ashwagandha is the most researched Ayurvedic adaptogen, with extensive clinical evidence for reducing cortisol, improving stress resilience, and supporting thyroid and adrenal function. Chronic stress and elevated cortisol directly impair pelvic floor function by maintaining the nervous system in a sympathetic state that prevents pelvic muscle relaxation. Multiple RCTs have confirmed its ability to reduce anxiety, improve sleep, and lower cortisol, all of which support pelvic floor healing.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/ashwagandha.webp',
    tags: ['adaptogen', 'cortisol', 'stress', 'nervous-system', 'thyroid'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Stress reduction and nervous system regulation',
  },
  {
    id: 'triphala',
    name: 'Triphala',
    category: 'Ayurvedic Herbs',
    subcategory: 'Digestive Tonics',
    description: 'Triphala is a classical Ayurvedic formula of three fruits (amalaki, bibhitaki, haritaki) used as a gentle bowel tonic and digestive support that is directly relevant to pelvic floor health. Chronic constipation and straining are among the most damaging habits for the pelvic floor, contributing to prolapse, hemorrhoids, and pudendal nerve irritation. Triphala\'s gentle laxative and prebiotic effects normalize bowel function without creating dependency, reducing the straining that damages pelvic floor structures.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/triphala.webp',
    tags: ['Ayurveda', 'constipation', 'bowel-health', 'prolapse-prevention', 'digestive'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Bowel regularity and constipation relief',
  },
  {
    id: 'brahmi',
    name: 'Brahmi (Bacopa monnieri)',
    category: 'Ayurvedic Herbs',
    subcategory: 'Nervines',
    description: 'Brahmi is the primary Ayurvedic nervine tonic, used to calm the nervous system, reduce anxiety, and improve cognitive function. The pelvic floor is profoundly influenced by the autonomic nervous system, and chronic anxiety maintains a hypertonic pelvic floor that resists relaxation. Bacosides, brahmi\'s active compounds, have demonstrated anxiolytic effects comparable to benzodiazepines in some studies, without the dependency risk.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/brahmi.webp',
    tags: ['Ayurveda', 'nervine', 'anxiety', 'hypertonic-pelvic-floor', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Nervous system calm and hypertonic pelvic floor',
  },
  // ─── WESTERN HERBS ────────────────────────────────────────────────────────
  {
    id: 'cramp-bark',
    name: 'Cramp Bark (Viburnum opulus)',
    category: 'Western Herbs',
    subcategory: 'Antispasmodics',
    description: 'Cramp bark is one of the most effective Western herbal antispasmodics for the uterus and pelvic floor, used for menstrual cramping, vaginismus, and hypertonic pelvic floor conditions. Its active compounds viopudial and scopoletin relax smooth and skeletal muscle, reducing spasm and pain without sedation. It is particularly useful for the type of pelvic floor tension that worsens with anxiety and stress.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/cramp-bark.webp',
    tags: ['antispasmodic', 'vaginismus', 'menstrual-pain', 'hypertonic-pelvic-floor', 'muscle-relaxant'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine and pelvic muscle spasm',
  },
  {
    id: 'black-cohosh',
    name: 'Black Cohosh (Actaea racemosa)',
    category: 'Western Herbs',
    subcategory: 'Menopause Support',
    description: 'Black cohosh is the most researched Western herb for menopausal symptoms, with multiple clinical trials demonstrating its ability to reduce hot flashes, night sweats, and vaginal dryness. Its mechanism involves serotonergic rather than estrogenic pathways, making it potentially safer than phytoestrogens for women with hormone-sensitive conditions. For pelvic floor health, its reduction of vaginal atrophy and dryness directly addresses pain with intercourse and urinary symptoms in menopause.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/black-cohosh.webp',
    tags: ['menopause', 'hot-flashes', 'vaginal-dryness', 'dyspareunia', 'Western-herbs'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Menopausal symptoms and vaginal atrophy',
  },
  {
    id: 'chaste-tree',
    name: 'Chaste Tree Berry (Vitex agnus-castus)',
    category: 'Western Herbs',
    subcategory: 'Hormonal Regulators',
    description: 'Vitex is the most researched Western herb for PMS, PMDD, and progesterone deficiency, with multiple clinical trials demonstrating its ability to reduce luteal phase symptoms by normalizing the LH/FSH ratio and supporting progesterone production. Progesterone deficiency contributes to pelvic floor dysfunction through its effects on connective tissue laxity, bladder sensitivity, and pelvic pain. It requires 3-6 months of consistent use to show full effect.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/vitex.webp',
    tags: ['PMS', 'PMDD', 'progesterone', 'hormonal-balance', 'Western-herbs'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PMS and progesterone deficiency',
  },
  {
    id: 'corn-silk',
    name: 'Corn Silk (Zea mays)',
    category: 'Western Herbs',
    subcategory: 'Urinary Demulcents',
    description: 'Corn silk is a gentle urinary demulcent and diuretic used for bladder irritation, urinary frequency, and mild urinary tract infections. Its mucilaginous compounds coat and soothe the bladder lining, reducing the urgency and burning associated with interstitial cystitis and overactive bladder. It is one of the safest urinary herbs for long-term use and is appropriate for women with sensitive bladders who react to many foods and supplements.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/corn-silk.webp',
    tags: ['urinary-demulcent', 'interstitial-cystitis', 'overactive-bladder', 'UTI', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Bladder soothing and urinary frequency',
  },
  {
    id: 'uva-ursi',
    name: 'Uva Ursi (Arctostaphylos uva-ursi)',
    category: 'Western Herbs',
    subcategory: 'Urinary Antiseptics',
    description: 'Uva ursi is a traditional urinary antiseptic herb containing arbutin, which converts to hydroquinone in alkaline urine and has demonstrated antibacterial activity against common UTI pathogens. It is used for acute urinary tract infections and as a preventive for recurrent UTIs that contribute to pelvic floor dysfunction through chronic inflammation. It requires an alkaline urine pH to activate, so it is often combined with sodium bicarbonate or dietary alkalinization.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/uva-ursi.webp',
    tags: ['UTI', 'urinary-antiseptic', 'recurrent-UTI', 'bladder-health', 'Western-herbs'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Urinary tract infection and prevention',
  },
  {
    id: 'red-raspberry-leaf',
    name: 'Red Raspberry Leaf',
    category: 'Western Herbs',
    subcategory: 'Uterine Tonics',
    description: 'Red raspberry leaf is a traditional uterine tonic used throughout pregnancy and postpartum recovery for its ability to tone uterine muscle and support pelvic floor strength. Its fragarine alkaloid has demonstrated uterine-toning effects, and its high mineral content (calcium, magnesium, iron) supports muscle function throughout the pelvic region. It is widely used in the third trimester to prepare the uterus for labor and postpartum for uterine involution.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/red-raspberry-leaf.webp',
    tags: ['uterine-tonic', 'postpartum', 'pregnancy', 'pelvic-floor-strength', 'Western-herbs'],
    evidenceLevel: 'traditional',
    primaryBenefit: 'Uterine tone and postpartum recovery',
  },
  // ─── ADDITIONAL SUPPLEMENTS ───────────────────────────────────────────────
  {
    id: 'hyaluronic-acid',
    name: 'Hyaluronic Acid (Oral)',
    category: 'Connective Tissue Support',
    subcategory: 'Joint & Tissue Hydration',
    description: 'Oral hyaluronic acid supplementation has demonstrated the ability to increase systemic hyaluronan levels, supporting the hydration and elasticity of connective tissues throughout the body including the pelvic floor fascia and vaginal epithelium. Clinical studies have shown improvement in vaginal dryness and dyspareunia with oral HA supplementation, making it a non-hormonal option for women who cannot use estrogen. It works synergistically with collagen peptides and vitamin C for comprehensive pelvic connective tissue support.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/hyaluronic-acid.webp',
    tags: ['connective-tissue', 'vaginal-dryness', 'dyspareunia', 'tissue-hydration', 'menopause'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Vaginal tissue hydration and connective tissue support',
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    category: 'Anti-Inflammatory',
    subcategory: 'Polyphenols',
    description: 'Resveratrol is a polyphenol with potent anti-inflammatory, antioxidant, and estrogen-modulating properties relevant to endometriosis, PCOS, and chronic pelvic inflammation. Multiple studies have demonstrated its ability to reduce endometrial lesion size, lower inflammatory markers, and modulate estrogen receptor activity. It activates SIRT1 pathways that regulate cellular aging, inflammation, and mitochondrial function in pelvic floor tissues.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/resveratrol.webp',
    tags: ['endometriosis', 'PCOS', 'anti-inflammatory', 'estrogen-modulation', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Endometriosis and chronic pelvic inflammation',
  },
  {
    id: 'quercetin',
    name: 'Quercetin',
    category: 'Anti-Inflammatory',
    subcategory: 'Flavonoids',
    description: 'Quercetin is a flavonoid with mast cell-stabilizing properties that make it particularly relevant for interstitial cystitis, vulvodynia, and other conditions involving mast cell activation in pelvic tissues. A clinical trial published in the Journal of Urology demonstrated significant improvement in IC symptoms with quercetin supplementation. It also has anti-inflammatory, antioxidant, and antiviral properties that support overall pelvic tissue health.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/quercetin.webp',
    tags: ['interstitial-cystitis', 'vulvodynia', 'mast-cell', 'anti-inflammatory', 'bladder-health'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Interstitial cystitis and mast cell stabilization',
  },
  {
    id: 'pycnogenol',
    name: 'Pycnogenol (Pine Bark Extract)',
    category: 'Anti-Inflammatory',
    subcategory: 'Proanthocyanidins',
    description: 'Pycnogenol is a standardized extract of French maritime pine bark with potent anti-inflammatory, antioxidant, and vascular-protective properties. Clinical trials have demonstrated its efficacy for endometriosis pain, dysmenorrhea, and pelvic congestion syndrome by reducing prostaglandin synthesis and improving pelvic microcirculation. It also supports collagen synthesis and vascular integrity in pelvic tissues.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/pycnogenol.webp',
    tags: ['endometriosis', 'dysmenorrhea', 'pelvic-congestion', 'anti-inflammatory', 'vascular'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Endometriosis pain and pelvic circulation',
  },
  {
    id: 'n-acetyl-cysteine',
    name: 'N-Acetyl Cysteine (NAC)',
    category: 'Anti-Inflammatory',
    subcategory: 'Antioxidants',
    description: 'NAC is a precursor to glutathione, the body\'s master antioxidant, and has demonstrated clinical efficacy for endometriosis, PCOS, and ovarian cyst reduction in multiple trials. A 2013 Italian trial found NAC more effective than placebo for endometriosis pain and cyst reduction, with some women avoiding surgery. It also supports liver detoxification of excess estrogens, which is relevant to estrogen-driven pelvic conditions.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/nac.webp',
    tags: ['endometriosis', 'PCOS', 'glutathione', 'estrogen-detox', 'antioxidant'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Endometriosis and PCOS support',
  },
  {
    id: 'berberine',
    name: 'Berberine',
    category: 'Metabolic Support',
    subcategory: 'Alkaloids',
    description: 'Berberine is an alkaloid found in goldenseal, barberry, and Oregon grape with demonstrated efficacy for PCOS, insulin resistance, and gut dysbiosis — all of which significantly impact pelvic floor health. Multiple meta-analyses have confirmed its ability to improve insulin sensitivity, reduce androgens in PCOS, and normalize menstrual cycles. Its antimicrobial properties also support vaginal microbiome health by reducing pathogenic bacteria and yeast.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/berberine.webp',
    tags: ['PCOS', 'insulin-resistance', 'vaginal-microbiome', 'gut-health', 'metabolic'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PCOS and insulin resistance',
  },
  {
    id: 'inositol',
    name: 'Myo-Inositol + D-Chiro-Inositol',
    category: 'Metabolic Support',
    subcategory: 'Insulin Sensitizers',
    description: 'The combination of myo-inositol and D-chiro-inositol in a 40:1 ratio is the most evidence-based nutritional intervention for PCOS, with multiple RCTs demonstrating improvements in insulin sensitivity, ovarian function, androgen levels, and menstrual regularity. PCOS-related hormonal imbalances directly affect pelvic floor function through their effects on connective tissue, bladder sensitivity, and chronic inflammation. It is considered a first-line nutritional intervention for PCOS by many integrative practitioners.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/inositol.webp',
    tags: ['PCOS', 'insulin-resistance', 'ovarian-function', 'hormonal-balance', 'fertility'],
    evidenceLevel: 'strong',
    primaryBenefit: 'PCOS and ovarian function',
  },
  {
    id: 'dim',
    name: 'DIM (Diindolylmethane)',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Metabolism',
    description: 'DIM is a compound derived from cruciferous vegetables that supports the conversion of estradiol to the less potent 2-hydroxyestrone pathway, reducing estrogen dominance and its downstream effects on pelvic tissues. Estrogen dominance contributes to endometriosis, fibroids, adenomyosis, and heavy periods — all of which cause pelvic floor dysfunction. It works synergistically with calcium D-glucarate and sulforaphane for comprehensive estrogen metabolism support.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/dim.webp',
    tags: ['estrogen-dominance', 'endometriosis', 'fibroids', 'hormonal-balance', 'detox'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen metabolism and dominance',
  },
  {
    id: 'calcium-d-glucarate',
    name: 'Calcium D-Glucarate',
    category: 'Hormonal Balance',
    subcategory: 'Estrogen Detox',
    description: 'Calcium D-glucarate inhibits beta-glucuronidase, an enzyme produced by gut bacteria that reactivates conjugated estrogens in the intestine, allowing them to be reabsorbed rather than excreted. Elevated beta-glucuronidase activity contributes to estrogen recirculation and dominance, which drives endometriosis, fibroids, and hormonal pelvic pain. It is a foundational supplement for estrogen detoxification pathways and is often combined with DIM and sulforaphane.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/calcium-d-glucarate.webp',
    tags: ['estrogen-detox', 'gut-health', 'endometriosis', 'fibroids', 'hormonal-balance'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Estrogen recirculation and gut-liver detox axis',
  },
  {
    id: 'probiotics-vaginal',
    name: 'Vaginal Probiotic (Lactobacillus reuteri + rhamnosus)',
    category: 'Microbiome Support',
    subcategory: 'Vaginal Probiotics',
    description: 'The vaginal microbiome is dominated by Lactobacillus species that maintain an acidic pH protecting against bacterial vaginosis, yeast infections, and UTIs — all of which cause pelvic floor dysfunction through inflammation and pain. Oral supplementation with L. reuteri RC-14 and L. rhamnosus GR-1 has the strongest clinical evidence for colonizing the vaginal tract and reducing recurrent BV and UTIs. A healthy vaginal microbiome also supports comfortable intercourse and reduces vulvodynia.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/vaginal-probiotic.webp',
    tags: ['vaginal-microbiome', 'BV', 'UTI', 'yeast-infection', 'vulvodynia'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Vaginal microbiome and recurrent infections',
  },
  {
    id: 'boric-acid-suppositories',
    name: 'Boric Acid Suppositories',
    category: 'Microbiome Support',
    subcategory: 'Vaginal pH',
    description: 'Boric acid vaginal suppositories are a clinically validated treatment for recurrent bacterial vaginosis and vulvovaginal candidiasis, particularly azole-resistant Candida glabrata strains. The CDC includes boric acid in its BV treatment guidelines, and multiple studies confirm 70-80% efficacy for recurrent BV when used as maintenance therapy. By restoring vaginal pH and disrupting biofilm, they reduce the chronic inflammation that contributes to vulvodynia and pelvic floor dysfunction.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/boric-acid.webp',
    tags: ['BV', 'yeast-infection', 'vaginal-pH', 'recurrent-infections', 'vulvodynia'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Recurrent BV and vaginal pH restoration',
  },
  {
    id: 'serrapeptase',
    name: 'Serrapeptase',
    category: 'Systemic Enzymes',
    subcategory: 'Proteolytic Enzymes',
    description: 'Serrapeptase is a proteolytic enzyme derived from silkworm bacteria with demonstrated anti-inflammatory, fibrinolytic, and scar-dissolving properties relevant to endometriosis adhesions, post-surgical scar tissue, and pelvic fibrosis. It breaks down non-living tissue including fibrin, scar tissue, and inflammatory proteins without affecting living tissue. Clinical studies have shown its efficacy for reducing post-surgical adhesions and chronic inflammatory conditions.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/serrapeptase.webp',
    tags: ['endometriosis', 'adhesions', 'scar-tissue', 'anti-inflammatory', 'fibrinolytic'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Adhesions and scar tissue dissolution',
  },
  {
    id: 'boswellia',
    name: 'Boswellia (Frankincense)',
    category: 'Anti-Inflammatory',
    subcategory: 'Resins',
    description: 'Boswellia serrata contains boswellic acids that specifically inhibit 5-LOX (5-lipoxygenase), an inflammatory enzyme pathway not targeted by NSAIDs, making it complementary to conventional anti-inflammatory approaches for endometriosis and chronic pelvic pain. Clinical trials have demonstrated its efficacy for inflammatory bowel disease, arthritis, and asthma, with emerging research for endometriosis and pelvic inflammation. AKBA (acetyl-11-keto-beta-boswellic acid) is the most potent anti-inflammatory compound.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/boswellia.webp',
    tags: ['anti-inflammatory', 'endometriosis', '5-LOX', 'chronic-pain', 'frankincense'],
    evidenceLevel: 'moderate',
    primaryBenefit: '5-LOX inflammation and endometriosis pain',
  },
  {
    id: 'lions-mane',
    name: "Lion's Mane Mushroom",
    category: 'Nervous System Support',
    subcategory: 'Nootropics',
    description: 'Lion\'s mane contains hericenones and erinacines that stimulate nerve growth factor (NGF) production, supporting nerve repair and regeneration relevant to pudendal neuralgia, pelvic nerve damage, and post-surgical nerve recovery. Pudendal nerve dysfunction is a common and underdiagnosed cause of chronic pelvic pain, and supporting nerve health through NGF stimulation may aid recovery. It also has anti-inflammatory and gut-supportive properties.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/lions-mane.webp',
    tags: ['nerve-repair', 'pudendal-neuralgia', 'NGF', 'neuropathy', 'mushroom'],
    evidenceLevel: 'emerging',
    primaryBenefit: 'Nerve repair and pudendal neuralgia',
  },
  {
    id: 'rhodiola',
    name: 'Rhodiola Rosea',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Rhodiola is a Scandinavian adaptogen with strong clinical evidence for reducing fatigue, burnout, and stress-related exhaustion that commonly accompanies chronic pelvic pain conditions. Its rosavins and salidroside regulate cortisol, support HPA axis function, and improve stress resilience. For women with pelvic floor dysfunction driven by chronic stress and nervous system dysregulation, rhodiola addresses the upstream cause rather than just the symptoms.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/rhodiola.webp',
    tags: ['adaptogen', 'fatigue', 'cortisol', 'HPA-axis', 'stress'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Fatigue and stress-related adrenal exhaustion',
  },
  {
    id: 'maca',
    name: 'Maca Root (Lepidium meyenii)',
    category: 'Hormonal Balance',
    subcategory: 'Endocrine Adaptogens',
    description: 'Maca is a Peruvian root vegetable with adaptogenic effects on the endocrine system, supporting hormonal balance without containing phytoestrogens or directly affecting hormone levels. Clinical trials have demonstrated improvements in menopausal symptoms, libido, and sexual function in postmenopausal women. For pelvic floor health, its support of sexual function, energy, and hormonal balance makes it relevant for women experiencing pelvic floor dysfunction alongside hormonal transitions.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/maca.webp',
    tags: ['hormonal-balance', 'menopause', 'libido', 'sexual-function', 'adaptogen'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Hormonal balance and sexual function',
  },
  {
    id: 'evening-primrose',
    name: 'Evening Primrose Oil',
    category: 'Essential Fatty Acids',
    subcategory: 'GLA Sources',
    description: 'Evening primrose oil is rich in gamma-linolenic acid (GLA), an omega-6 fatty acid that reduces inflammatory prostaglandins relevant to menstrual pain, endometriosis, and pelvic inflammation. It is particularly effective for PMS-related breast tenderness, mood symptoms, and dysmenorrhea when taken throughout the menstrual cycle. GLA also supports skin and mucosal membrane health, which is relevant to vaginal tissue integrity and comfort.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/evening-primrose.webp',
    tags: ['GLA', 'PMS', 'dysmenorrhea', 'endometriosis', 'mucosal-health'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'PMS and prostaglandin-driven pelvic pain',
  },
  {
    id: 'iodine',
    name: "Iodine (Lugol's or Nascent)",
    category: 'Thyroid & Hormonal Support',
    subcategory: 'Minerals',
    description: 'Iodine deficiency is widespread and directly impacts thyroid function, ovarian health, and breast tissue — all of which influence pelvic floor function through hormonal pathways. The ovaries and uterus concentrate iodine, and deficiency has been linked to fibrocystic breast disease, ovarian cysts, and estrogen dominance. Supplementation should be guided by testing and started at low doses with cofactors including selenium, magnesium, and vitamin C.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/iodine.webp',
    tags: ['thyroid', 'iodine-deficiency', 'ovarian-health', 'estrogen-dominance', 'hormonal'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Thyroid and ovarian iodine support',
  },
  {
    id: 'selenium',
    name: 'Selenium (Selenomethionine)',
    category: 'Thyroid & Hormonal Support',
    subcategory: 'Minerals',
    description: 'Selenium is essential for thyroid hormone conversion (T4 to T3) and for the selenoprotein antioxidant enzymes including glutathione peroxidase that protect pelvic tissues from oxidative damage. Hashimoto\'s thyroiditis, which affects millions of women, is associated with pelvic floor dysfunction through hypothyroid effects on connective tissue, bladder function, and constipation. Selenomethionine is the most bioavailable form, and 200mcg daily has demonstrated reduction in thyroid antibodies in clinical trials.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/selenium.webp',
    tags: ['thyroid', 'Hashimotos', 'antioxidant', 'glutathione', 'hormonal'],
    evidenceLevel: 'strong',
    primaryBenefit: 'Thyroid health and antioxidant protection',
  },
  {
    id: 'passionflower',
    name: 'Passionflower (Passiflora incarnata)',
    category: 'Pain & Nervous System',
    subcategory: 'Nervines',
    description: 'Passionflower is a gentle anxiolytic and nervine sedative with clinical evidence for anxiety, insomnia, and nervous system hyperactivation — all of which maintain pelvic floor hypertonicity. A clinical trial found it comparable to oxazepam for generalized anxiety disorder, without the dependency risk. For pelvic floor health, its ability to reduce sympathetic nervous system dominance supports pelvic muscle relaxation and pain reduction.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/passionflower.webp',
    tags: ['anxiety', 'nervine', 'hypertonic-pelvic-floor', 'sleep', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Anxiety and nervous system hyperactivation',
  },
  {
    id: 'valerian',
    name: 'Valerian Root',
    category: 'Pain & Nervous System',
    subcategory: 'Nervines',
    description: 'Valerian root is a traditional sedative and nervine herb with GABAergic mechanisms that reduce anxiety, improve sleep quality, and relax smooth and skeletal muscle. Poor sleep is a significant driver of pelvic floor dysfunction through its effects on pain sensitivity, cortisol regulation, and tissue repair. It is particularly useful for women whose pelvic floor tension worsens at night or is associated with sleep disturbance and anxiety.',
    asin: 'B00NQ3NKZS',
    imageKey: 'supplements/valerian.webp',
    tags: ['sleep', 'anxiety', 'GABA', 'muscle-relaxant', 'nervous-system'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Sleep quality and nervous system relaxation',
  },
  {
    id: 'reishi',
    name: 'Reishi Mushroom (Ganoderma lucidum)',
    category: 'Nervous System Support',
    subcategory: 'Adaptogens',
    description: 'Reishi is an adaptogenic mushroom used in TCM for over 2,000 years for its immune-modulating, anti-inflammatory, and nervous system calming properties. Its triterpenes and beta-glucans reduce inflammatory cytokines relevant to autoimmune pelvic conditions, endometriosis, and IC. It is particularly valued for its ability to calm the nervous system and support sleep without sedation, addressing the anxiety-pelvic floor tension cycle.',
    asin: 'B00014GKRE',
    imageKey: 'supplements/reishi.webp',
    tags: ['adaptogen', 'immune-modulation', 'endometriosis', 'anxiety', 'sleep'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Immune modulation and nervous system calm',
  },
  {
    id: 'black-seed-oil',
    name: 'Black Seed Oil (Nigella sativa)',
    category: 'Anti-Inflammatory',
    subcategory: 'Seed Oils',
    description: 'Black seed oil contains thymoquinone, one of the most potent natural anti-inflammatory and immunomodulatory compounds, with demonstrated efficacy for autoimmune conditions, endometriosis, and chronic inflammatory pain. Multiple studies have shown its ability to reduce inflammatory cytokines, modulate immune function, and reduce pain in conditions relevant to pelvic floor health. It is used in both Islamic medicine and modern integrative practice for endometriosis, PCOS, and chronic pelvic inflammation.',
    asin: 'B07BKQPVHQ',
    imageKey: 'supplements/black-seed-oil.webp',
    tags: ['anti-inflammatory', 'endometriosis', 'autoimmune', 'PCOS', 'thymoquinone'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Autoimmune inflammation and endometriosis',
  },
  {
    id: 'nattokinase',
    name: 'Nattokinase',
    category: 'Systemic Enzymes',
    subcategory: 'Fibrinolytic Enzymes',
    description: 'Nattokinase is a fibrinolytic enzyme from fermented soybeans (natto) that dissolves fibrin clots and supports healthy blood viscosity, with relevance to pelvic congestion syndrome, endometriosis, and conditions involving poor pelvic circulation. It has demonstrated cardiovascular and anti-thrombotic effects in clinical research, and is used in integrative medicine for conditions involving fibrin accumulation in pelvic tissues. It works synergistically with serrapeptase for adhesion and scar tissue management.',
    asin: 'B07FKJQMXQ',
    imageKey: 'supplements/nattokinase.webp',
    tags: ['fibrinolytic', 'pelvic-congestion', 'endometriosis', 'circulation', 'adhesions'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Fibrin dissolution and pelvic circulation',
  },
  {
    id: 'holy-basil',
    name: 'Holy Basil / Tulsi (Ocimum tenuiflorum)',
    category: 'Energy & Adrenal Support',
    subcategory: 'Adaptogens',
    description: 'Holy basil (tulsi) is a sacred Ayurvedic adaptogen with cortisol-lowering, anti-inflammatory, and blood sugar-regulating properties relevant to stress-driven pelvic floor dysfunction and PCOS. Clinical trials have demonstrated its ability to reduce cortisol, fasting glucose, and anxiety, addressing the metabolic and stress components of pelvic conditions. It is particularly valued for its gentle, cumulative effect on the nervous system and its safety for long-term use.',
    asin: 'B07CQMKBPZ',
    imageKey: 'supplements/holy-basil.webp',
    tags: ['adaptogen', 'cortisol', 'PCOS', 'blood-sugar', 'Ayurveda'],
    evidenceLevel: 'moderate',
    primaryBenefit: 'Cortisol regulation and PCOS support',
  },
"""

with open('src/data/supplements.ts', 'r') as f:
    content = f.read()

marker = '];\n\nexport default supplements;\n'
if marker not in content:
    print("ERROR: marker not found")
    exit(1)

new_content = content.replace(marker, NEW + '\n' + marker)

with open('src/data/supplements.ts', 'w') as f:
    f.write(new_content)

import re
count = len(re.findall(r"^\s+id:", new_content, re.MULTILINE))
print(f"SUCCESS: {count} total supplement entries")
